CREATE TABLE denuncias.log_guardar_denuncia
(
id_log_guardar_denuncia INT generated by default as identity PRIMARY KEY,
ts_utc_inicio timestamp NOT NULL,
client_net_address varchar(100),
system_user varchar(128),
current_user varchar(128),
in_denuncia_json text NULL,
out_resp_json text NULL,
ts_utc_fin timestamp NULL,
error text NULL
)
