-- =============================================================================
-- SIP â€” Migration V0002__nuevo_esquema_auth
-- =============================================================================
-- VersiÃ³n: 4.0 v2 (incremental sobre V0001__baseline_sip)
-- Compatible: SQL Server 2017+ (forward-compatible 2022)
-- Depende de: V0001__baseline_sip.sql (esquema organizacion.funcionario)
--
-- ALCANCE:
-- Crea el esquema `auth` con el modelo de identidad, sesiones (refresh
-- tokens), RBAC (roles, perfiles, permisos, niveles de seguridad) y
-- configuraciÃ³n global del sistema de autenticaciÃ³n (auth.parametro).
--
-- FLUJO DE AUTENTICACIÃ“N/AUTORIZACIÃ“N:
-- 1. Sistema externo entrega: numero_identificacion + token JWT
-- 2. SIP busca en personas.persona por nÃºmero de identificaciÃ³n
-- â†’ obtiene id_persona
-- 3. SIP busca en organizacion.funcionario por id_persona
-- â†’ obtiene id_funcionario
-- 4. SIP busca en auth.usuario por id_funcionario
-- â†’ obtiene id_usuario y sus perfiles/roles/permisos efectivos
--
-- CONVENCIONES (heredadas del baseline V0001):
-- - PKs nombradas id_<tabla> con generated by default as generated by default as identity
-- - Naming de constraints en lowercase (pk_, fk_, uq_, ix_, ck_, ux_)
-- - Tipos: NVARCHAR para texto con posibles caracteres especiales (nombres,
-- descripciones, emails); VARCHAR para identificadores tÃ©cnicos ASCII
-- (siglas, cÃ³digos, hashes, IPs, identificadores AD)
-- - Booleans como SMALLINT + CONSTRAINT ck_<tabla>_<col> CHECK (col IN (0,1))
-- - Timestamps en UTC con DEFAULT CURRENT_TIMESTAMP
--
-- ESTRUCTURA DEL ARCHIVO:
-- PASO 1 â€” Esquema
-- PASO 2 â€” Tablas (sÃ³lo CREATE TABLE con PK, UQ, CK; sin FKs)
-- PASO 3 â€” Ãndices
-- PASO 4 â€” Foreign keys internas (intra-esquema auth)
-- PASO 5 â€” Foreign keys cruzadas (a otros esquemas)
-- PASO 6 â€” Descripciones (sys.sp_addextendedproperty idempotente)
--
-- DECISIONES PENDIENTES:
-- - auth.perfil.id_usuario_auditoria: presente en el modelo recibido,
-- se mantiene como vino. Su FK NO se declara hasta que se confirme su
-- semÃ¡ntica.
-- - AuditorÃ­a general (creado_por/creado_en/modificado_por/modificado_en):
-- no se aplica en esta migration; pendiente para migration transversal.
-- =============================================================================
SET ANSI_NULLS ON;
SET ANSI_WARNINGS ON;
SET ANSI_PADDING ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;


-- =============================================================================
-- PASO 1 â€” ESQUEMA
-- =============================================================================

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'auth')
 EXEC('CREATE SCHEMA auth');


-- =============================================================================
-- PASO 2 â€” TABLAS
-- =============================================================================
-- Cada CREATE TABLE incluye sÃ³lo la PK, UNIQUE constraints y CHECK constraints.
-- Las FKs (internas y cruzadas) se declaran en pasos posteriores como ALTER
-- TABLE para mantener separadas las preocupaciones.
-- =============================================================================

-- Tabla: auth.usuario
CREATE TABLE auth.usuario (
 id_usuario INTEGER generated by default as generated by default as identity NOT NULL,
 id_funcionario INTEGER NOT NULL,
 username VARCHAR(100) NOT NULL,
 activo SMALLINT NOT NULL DEFAULT 1
 CONSTRAINT ck_usuario_activo CHECK (activo IN (0,1)),
 fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 auth_provider VARCHAR(16) NOT NULL DEFAULT 'AD'
 CONSTRAINT ck_usuario_auth_provider CHECK (auth_provider IN ('AD','EXTERNO','LOCAL')),
 nombre_mostrar varchar(200) NULL,
 email varchar(256) NULL,
 dominio VARCHAR(64) NULL,
 upn VARCHAR(256) NULL,
 ad_sid VARCHAR(128) NULL,
 fecha_ultimo_acceso timestamp NULL,
 CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
 CONSTRAINT uq_usuario_username UNIQUE (username),
 CONSTRAINT uq_usuario_funcionario UNIQUE (id_funcionario)
);


-- Tabla: auth.perfil
CREATE TABLE auth.perfil (
 id_perfil INTEGER generated by default as generated by default as identity NOT NULL,
 id_usuario_auditoria INTEGER NULL,
 nombre varchar(100) NOT NULL,
 sigla VARCHAR(10) NOT NULL,
 descripcion varchar(500) NULL,
 CONSTRAINT pk_perfil PRIMARY KEY (id_perfil),
 CONSTRAINT uq_perfil_nombre UNIQUE (nombre),
 CONSTRAINT uq_perfil_sigla UNIQUE (sigla)
);


-- Tabla: auth.rol
CREATE TABLE auth.rol (
 id_rol INTEGER generated by default as generated by default as identity NOT NULL,
 nombre varchar(100) NOT NULL,
 sigla VARCHAR(10) NOT NULL,
 CONSTRAINT pk_rol PRIMARY KEY (id_rol),
 CONSTRAINT uq_rol_nombre UNIQUE (nombre),
 CONSTRAINT uq_rol_sigla UNIQUE (sigla)
);


-- Tabla: auth.nivel_seguridad
CREATE TABLE auth.nivel_seguridad (
 id_nivel_seguridad INTEGER generated by default as generated by default as identity NOT NULL,
 nivel INTEGER NOT NULL,
 descripcion varchar(500) NULL,
 CONSTRAINT pk_nivel_seguridad PRIMARY KEY (id_nivel_seguridad),
 CONSTRAINT uq_nivel_seguridad_nivel UNIQUE (nivel)
);


-- Tabla: auth.permiso
CREATE TABLE auth.permiso (
 id_permiso INTEGER generated by default as generated by default as identity NOT NULL,
 codigo_funcion VARCHAR(10) NOT NULL,
 nombre varchar(150) NOT NULL,
 categoria varchar(100) NOT NULL,
 CONSTRAINT pk_permiso PRIMARY KEY (id_permiso),
 CONSTRAINT uq_permiso_codigo_funcion UNIQUE (codigo_funcion)
);


-- Tabla: auth.refresh_token
CREATE TABLE auth.refresh_token (
 id_refresh_token INTEGER generated by default as generated by default as identity NOT NULL,
 id_usuario INTEGER NOT NULL,
 token_hash VARBINARY(32) NOT NULL,
 fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 fecha_expiracion timestamp NOT NULL,
 fecha_revocacion timestamp NULL,
 id_refresh_token_reemplazo INTEGER NULL,
 ip_creacion VARCHAR(64) NULL,
 user_agent varchar(1000) NULL,
 CONSTRAINT pk_refresh_token PRIMARY KEY (id_refresh_token)
);


-- Tabla: auth.usuario_perfil
CREATE TABLE auth.usuario_perfil (
 id_usuario INTEGER NOT NULL,
 id_perfil INTEGER NOT NULL,
 CONSTRAINT pk_usuario_perfil PRIMARY KEY (id_usuario, id_perfil)
);


-- Tabla: auth.perfil_rol
CREATE TABLE auth.perfil_rol (
 id_perfil_rol INTEGER generated by default as generated by default as identity NOT NULL,
 id_perfil INTEGER NOT NULL,
 id_rol INTEGER NOT NULL,
 id_nivel_seguridad INTEGER NOT NULL,
 claim_code VARCHAR(20) NOT NULL,
 CONSTRAINT pk_perfil_rol PRIMARY KEY (id_perfil_rol),
 CONSTRAINT uq_perfil_rol_claim_code UNIQUE (claim_code),
 CONSTRAINT uq_perfil_rol_combinacion UNIQUE (id_perfil, id_rol, id_nivel_seguridad)
);


-- Tabla: auth.perfil_rol_permiso
CREATE TABLE auth.perfil_rol_permiso (
 id_perfil_rol_permiso INTEGER generated by default as generated by default as identity NOT NULL,
 id_perfil_rol INTEGER NOT NULL,
 id_permiso INTEGER NOT NULL,
 CONSTRAINT pk_perfil_rol_permiso PRIMARY KEY (id_perfil_rol_permiso),
 CONSTRAINT uq_perfil_rol_permiso_combinacion UNIQUE (id_perfil_rol, id_permiso)
);


-- Tabla: auth.parametro
-- ConfiguraciÃ³n global del sistema de autenticaciÃ³n. PatrÃ³n key-value con
-- tipado fuerte: cada parÃ¡metro tiene un nombre Ãºnico en formato
-- namespace.nombre (ej. login.intentos_maximos) y se almacena en la columna
-- que corresponde a su tipo (valor_numerico INTEGER o valor_varchar
-- NVARCHAR). El CHECK ck_parametro_tipo_valor garantiza coherencia.
-- Booleans se modelan con tipo_dato='BOOLEAN' y valor_numerico IN (0,1).
CREATE TABLE auth.parametro (
 id_parametro INTEGER generated by default as generated by default as identity NOT NULL,
 nombre_parametro VARCHAR(100) NOT NULL,
 tipo_dato VARCHAR(20) NOT NULL,
 valor_numerico INTEGER NULL,
 valor_varchar varchar(500) NULL,
 activo SMALLINT NOT NULL DEFAULT 1
 CONSTRAINT ck_parametro_activo CHECK (activo IN (0,1)),
 descripcion varchar(500) NULL,
 CONSTRAINT pk_parametro PRIMARY KEY (id_parametro),
 CONSTRAINT uq_parametro_nombre_parametro UNIQUE (nombre_parametro),
 CONSTRAINT ck_parametro_tipo_dato CHECK (tipo_dato IN ('NUMERICO','VARCHAR','BOOLEAN')),
 CONSTRAINT ck_parametro_tipo_valor CHECK (
 (tipo_dato = 'NUMERICO' AND valor_numerico IS NOT NULL AND valor_varchar IS NULL)
 OR (tipo_dato = 'BOOLEAN' AND valor_numerico IN (0,1) AND valor_varchar IS NULL)
 OR (tipo_dato = 'VARCHAR' AND valor_varchar IS NOT NULL AND valor_numerico IS NULL)
 )
);


-- =============================================================================
-- PASO 3 â€” ÃNDICES
-- =============================================================================

-- BÃºsqueda de tokens activos de un usuario (filtrado: no revocados)
CREATE INDEX ix_refresh_token_usuario_activos
 ON auth.refresh_token (id_usuario, fecha_expiracion)
 WHERE fecha_revocacion IS NULL;

-- BÃºsqueda por hash de token (validaciÃ³n en cada request)
CREATE UNIQUE INDEX ux_refresh_token_hash
 ON auth.refresh_token (token_hash);

-- Permisos por categorÃ­a (UI de administraciÃ³n)
CREATE INDEX ix_permiso_categoria
 ON auth.permiso (categoria);


-- =============================================================================
-- PASO 4 â€” FOREIGN KEYS INTERNAS (intra-esquema auth)
-- =============================================================================

-- refresh_token.id_usuario â†’ usuario
ALTER TABLE auth.refresh_token
 ADD CONSTRAINT fk_refresh_token_usuario
 FOREIGN KEY (id_usuario)
 REFERENCES auth.usuario (id_usuario);

-- refresh_token.id_refresh_token_reemplazo â†’ refresh_token (auto-FK)
ALTER TABLE auth.refresh_token
 ADD CONSTRAINT fk_refresh_token_reemplazo
 FOREIGN KEY (id_refresh_token_reemplazo)
 REFERENCES auth.refresh_token (id_refresh_token);

-- usuario_perfil.id_usuario â†’ usuario
ALTER TABLE auth.usuario_perfil
 ADD CONSTRAINT fk_usuario_perfil_usuario
 FOREIGN KEY (id_usuario)
 REFERENCES auth.usuario (id_usuario);

-- usuario_perfil.id_perfil â†’ perfil
ALTER TABLE auth.usuario_perfil
 ADD CONSTRAINT fk_usuario_perfil_perfil
 FOREIGN KEY (id_perfil)
 REFERENCES auth.perfil (id_perfil);

-- perfil_rol.id_perfil â†’ perfil
ALTER TABLE auth.perfil_rol
 ADD CONSTRAINT fk_perfil_rol_perfil
 FOREIGN KEY (id_perfil)
 REFERENCES auth.perfil (id_perfil);

-- perfil_rol.id_rol â†’ rol
ALTER TABLE auth.perfil_rol
 ADD CONSTRAINT fk_perfil_rol_rol
 FOREIGN KEY (id_rol)
 REFERENCES auth.rol (id_rol);

-- perfil_rol.id_nivel_seguridad â†’ nivel_seguridad
ALTER TABLE auth.perfil_rol
 ADD CONSTRAINT fk_perfil_rol_nivel_seguridad
 FOREIGN KEY (id_nivel_seguridad)
 REFERENCES auth.nivel_seguridad (id_nivel_seguridad);

-- perfil_rol_permiso.id_perfil_rol â†’ perfil_rol
ALTER TABLE auth.perfil_rol_permiso
 ADD CONSTRAINT fk_perfil_rol_permiso_perfil_rol
 FOREIGN KEY (id_perfil_rol)
 REFERENCES auth.perfil_rol (id_perfil_rol);

-- perfil_rol_permiso.id_permiso â†’ permiso
ALTER TABLE auth.perfil_rol_permiso
 ADD CONSTRAINT fk_perfil_rol_permiso_permiso
 FOREIGN KEY (id_permiso)
 REFERENCES auth.permiso (id_permiso);


-- =============================================================================
-- PASO 5 â€” FOREIGN KEYS CRUZADAS (a otros esquemas)
-- =============================================================================

-- usuario.id_funcionario â†’ organizacion.funcionario
ALTER TABLE auth.usuario
 ADD CONSTRAINT fk_usuario_funcionario
 FOREIGN KEY (id_funcionario)
 REFERENCES organizacion.funcionario (id_funcionario);


-- =============================================================================
-- PASO 6 â€” DESCRIPCIONES
-- =============================================================================
-- Cada bloque es idempotente: actualiza la descripciÃ³n si existe, la crea
-- si no existe.
-- =============================================================================

-- ----- Esquema -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=SCHEMA_ID(N'auth') AND class=3)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Identidad, sesiones (refresh tokens), RBAC (perfiles, roles, niveles de seguridad y permisos) y configuraciÃ³n global de autenticaciÃ³n.',
 @level0type=N'SCHEMA', @level0name=N'auth';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identidad, sesiones (refresh tokens), RBAC (perfiles, roles, niveles de seguridad y permisos) y configuraciÃ³n global de autenticaciÃ³n.',
 @level0type=N'SCHEMA', @level0name=N'auth';


-- ----- Tabla: usuario -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Identidad del usuario en el sistema. RelaciÃ³n 1:1 estricta con organizacion.funcionario: todo usuario es un funcionario y todo funcionario tiene a lo mÃ¡s un usuario.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identidad del usuario en el sistema. RelaciÃ³n 1:1 estricta con organizacion.funcionario: todo usuario es un funcionario y todo funcionario tiene a lo mÃ¡s un usuario.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario'),N'id_usuario',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del usuario. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'id_usuario';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del usuario. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'id_usuario';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario'),N'id_funcionario',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'FK a organizacion.funcionario. Obligatoria y Ãºnica (1:1). Vincula la identidad del usuario con el funcionario PDI.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'id_funcionario';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a organizacion.funcionario. Obligatoria y Ãºnica (1:1). Vincula la identidad del usuario con el funcionario PDI.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'id_funcionario';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario'),N'username',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Nombre de usuario Ãºnico. ASCII (sAMAccountName de AD o equivalente).',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'username';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Nombre de usuario Ãºnico. ASCII (sAMAccountName de AD o equivalente).',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'username';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario'),N'activo',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Indica si el usuario puede iniciar sesiÃ³n (1) o estÃ¡ deshabilitado (0). Default 1.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'activo';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Indica si el usuario puede iniciar sesiÃ³n (1) o estÃ¡ deshabilitado (0). Default 1.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'activo';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario'),N'fecha_creacion',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Timestamp UTC de creaciÃ³n del usuario. Default CURRENT_TIMESTAMP.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'fecha_creacion';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Timestamp UTC de creaciÃ³n del usuario. Default CURRENT_TIMESTAMP.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'fecha_creacion';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario'),N'auth_provider',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Origen de autenticaciÃ³n: AD (Active Directory), EXTERNO (otro sistema integrado) o LOCAL (sÃ³lo casos especiales). Default AD.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'auth_provider';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Origen de autenticaciÃ³n: AD (Active Directory), EXTERNO (otro sistema integrado) o LOCAL (sÃ³lo casos especiales). Default AD.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'auth_provider';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario'),N'nombre_mostrar',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Nombre para mostrar en la UI (displayName del directorio). Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'nombre_mostrar';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Nombre para mostrar en la UI (displayName del directorio). Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'nombre_mostrar';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario'),N'email',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Correo electrÃ³nico institucional del usuario. Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'email';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Correo electrÃ³nico institucional del usuario. Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'email';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario'),N'dominio',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Dominio AD/LDAP al que pertenece el usuario (NetBIOS o FQDN). Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'dominio';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Dominio AD/LDAP al que pertenece el usuario (NetBIOS o FQDN). Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'dominio';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario'),N'upn',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'User Principal Name (formato user@dominio.fqdn). Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'upn';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'User Principal Name (formato user@dominio.fqdn). Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'upn';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario'),N'ad_sid',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Security Identifier de Active Directory. Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'ad_sid';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Security Identifier de Active Directory. Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'ad_sid';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario'),N'fecha_ultimo_acceso',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Timestamp UTC del Ãºltimo login exitoso. Se actualiza por la aplicaciÃ³n.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'fecha_ultimo_acceso';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Timestamp UTC del Ãºltimo login exitoso. Se actualiza por la aplicaciÃ³n.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario',
 @level2type=N'COLUMN', @level2name=N'fecha_ultimo_acceso';


-- ----- Tabla: perfil -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'AgrupaciÃ³n de alto nivel de roles (ej. Detective, Jefe de Brigada, Operador BIDEMA). Un usuario puede tener uno o mÃ¡s perfiles.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'AgrupaciÃ³n de alto nivel de roles (ej. Detective, Jefe de Brigada, Operador BIDEMA). Un usuario puede tener uno o mÃ¡s perfiles.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil'),N'id_perfil',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del perfil. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil',
 @level2type=N'COLUMN', @level2name=N'id_perfil';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del perfil. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil',
 @level2type=N'COLUMN', @level2name=N'id_perfil';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil'),N'id_usuario_auditoria',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Columna de auditorÃ­a (semÃ¡ntica pendiente de definir). FK aÃºn no declarada.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil',
 @level2type=N'COLUMN', @level2name=N'id_usuario_auditoria';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Columna de auditorÃ­a (semÃ¡ntica pendiente de definir). FK aÃºn no declarada.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil',
 @level2type=N'COLUMN', @level2name=N'id_usuario_auditoria';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil'),N'nombre',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Nombre descriptivo del perfil. Ãšnico.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil',
 @level2type=N'COLUMN', @level2name=N'nombre';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Nombre descriptivo del perfil. Ãšnico.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil',
 @level2type=N'COLUMN', @level2name=N'nombre';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil'),N'sigla',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Sigla corta del perfil para uso operativo. Ãšnica.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil',
 @level2type=N'COLUMN', @level2name=N'sigla';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Sigla corta del perfil para uso operativo. Ãšnica.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil',
 @level2type=N'COLUMN', @level2name=N'sigla';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil'),N'descripcion',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'DescripciÃ³n extendida del perfil. Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil',
 @level2type=N'COLUMN', @level2name=N'descripcion';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'DescripciÃ³n extendida del perfil. Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil',
 @level2type=N'COLUMN', @level2name=N'descripcion';


-- ----- Tabla: rol -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.rol') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'FunciÃ³n especÃ­fica del sistema (ej. Crear denuncia, Aprobar diligencia). Se asigna a perfiles a travÃ©s de perfil_rol con un nivel de seguridad.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'rol';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FunciÃ³n especÃ­fica del sistema (ej. Crear denuncia, Aprobar diligencia). Se asigna a perfiles a travÃ©s de perfil_rol con un nivel de seguridad.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'rol';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.rol')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.rol'),N'id_rol',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del rol. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'rol',
 @level2type=N'COLUMN', @level2name=N'id_rol';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del rol. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'rol',
 @level2type=N'COLUMN', @level2name=N'id_rol';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.rol')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.rol'),N'nombre',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Nombre descriptivo del rol. Ãšnico.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'rol',
 @level2type=N'COLUMN', @level2name=N'nombre';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Nombre descriptivo del rol. Ãšnico.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'rol',
 @level2type=N'COLUMN', @level2name=N'nombre';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.rol')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.rol'),N'sigla',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Sigla corta del rol para uso operativo. Ãšnica.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'rol',
 @level2type=N'COLUMN', @level2name=N'sigla';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Sigla corta del rol para uso operativo. Ãšnica.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'rol',
 @level2type=N'COLUMN', @level2name=N'sigla';


-- ----- Tabla: nivel_seguridad -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.nivel_seguridad') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Califica el alcance/profundidad con que un perfil tiene un rol asignado. Permite gradar permisos sin multiplicar roles.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'nivel_seguridad';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Califica el alcance/profundidad con que un perfil tiene un rol asignado. Permite gradar permisos sin multiplicar roles.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'nivel_seguridad';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.nivel_seguridad')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.nivel_seguridad'),N'id_nivel_seguridad',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'nivel_seguridad',
 @level2type=N'COLUMN', @level2name=N'id_nivel_seguridad';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'nivel_seguridad',
 @level2type=N'COLUMN', @level2name=N'id_nivel_seguridad';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.nivel_seguridad')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.nivel_seguridad'),N'nivel',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Valor numÃ©rico del nivel. Ãšnico.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'nivel_seguridad',
 @level2type=N'COLUMN', @level2name=N'nivel';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Valor numÃ©rico del nivel. Ãšnico.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'nivel_seguridad',
 @level2type=N'COLUMN', @level2name=N'nivel';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.nivel_seguridad')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.nivel_seguridad'),N'descripcion',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'DescripciÃ³n del alcance del nivel. Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'nivel_seguridad',
 @level2type=N'COLUMN', @level2name=N'descripcion';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'DescripciÃ³n del alcance del nivel. Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'nivel_seguridad',
 @level2type=N'COLUMN', @level2name=N'descripcion';


-- ----- Tabla: permiso -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.permiso') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'AcciÃ³n atÃ³mica del sistema (ej. denuncia.crear, caso.aprobar). Es lo que finalmente el cÃ³digo consulta para autorizar operaciones.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'permiso';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'AcciÃ³n atÃ³mica del sistema (ej. denuncia.crear, caso.aprobar). Es lo que finalmente el cÃ³digo consulta para autorizar operaciones.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'permiso';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.permiso')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.permiso'),N'id_permiso',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del permiso. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'permiso',
 @level2type=N'COLUMN', @level2name=N'id_permiso';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del permiso. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'permiso',
 @level2type=N'COLUMN', @level2name=N'id_permiso';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.permiso')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.permiso'),N'codigo_funcion',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'CÃ³digo corto del permiso usado por el cÃ³digo de la aplicaciÃ³n. Ãšnico.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'permiso',
 @level2type=N'COLUMN', @level2name=N'codigo_funcion';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'CÃ³digo corto del permiso usado por el cÃ³digo de la aplicaciÃ³n. Ãšnico.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'permiso',
 @level2type=N'COLUMN', @level2name=N'codigo_funcion';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.permiso')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.permiso'),N'nombre',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Nombre descriptivo del permiso para mostrar en la UI de administraciÃ³n.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'permiso',
 @level2type=N'COLUMN', @level2name=N'nombre';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Nombre descriptivo del permiso para mostrar en la UI de administraciÃ³n.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'permiso',
 @level2type=N'COLUMN', @level2name=N'nombre';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.permiso')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.permiso'),N'categoria',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'CategorÃ­a del permiso para agrupar en la UI de administraciÃ³n.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'permiso',
 @level2type=N'COLUMN', @level2name=N'categoria';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'CategorÃ­a del permiso para agrupar en la UI de administraciÃ³n.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'permiso',
 @level2type=N'COLUMN', @level2name=N'categoria';


-- ----- Tabla: refresh_token -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.refresh_token') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'GestiÃ³n de refresh tokens del usuario. Token guardado como hash SHA-256 (32 bytes). Soporta rotaciÃ³n: cuando un token se reemplaza, se referencia al nuevo en id_refresh_token_reemplazo.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'GestiÃ³n de refresh tokens del usuario. Token guardado como hash SHA-256 (32 bytes). Soporta rotaciÃ³n: cuando un token se reemplaza, se referencia al nuevo en id_refresh_token_reemplazo.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.refresh_token')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.refresh_token'),N'id_refresh_token',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del token. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'id_refresh_token';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del token. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'id_refresh_token';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.refresh_token')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.refresh_token'),N'id_usuario',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'FK al usuario propietario del token.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'id_usuario';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK al usuario propietario del token.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'id_usuario';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.refresh_token')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.refresh_token'),N'token_hash',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Hash SHA-256 del refresh token (32 bytes). El token plano nunca se almacena.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'token_hash';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Hash SHA-256 del refresh token (32 bytes). El token plano nunca se almacena.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'token_hash';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.refresh_token')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.refresh_token'),N'fecha_creacion',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Timestamp UTC de emisiÃ³n del token. Default CURRENT_TIMESTAMP.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'fecha_creacion';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Timestamp UTC de emisiÃ³n del token. Default CURRENT_TIMESTAMP.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'fecha_creacion';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.refresh_token')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.refresh_token'),N'fecha_expiracion',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Timestamp UTC en que el token expira y deja de ser vÃ¡lido.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'fecha_expiracion';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Timestamp UTC en que el token expira y deja de ser vÃ¡lido.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'fecha_expiracion';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.refresh_token')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.refresh_token'),N'fecha_revocacion',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Timestamp UTC en que el token fue revocado (logout, rotaciÃ³n, compromiso). NULL = token activo.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'fecha_revocacion';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Timestamp UTC en que el token fue revocado (logout, rotaciÃ³n, compromiso). NULL = token activo.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'fecha_revocacion';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.refresh_token')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.refresh_token'),N'id_refresh_token_reemplazo',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Auto-FK al token que reemplazÃ³ a Ã©ste en una rotaciÃ³n. Permite trazar la cadena de refresh.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'id_refresh_token_reemplazo';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Auto-FK al token que reemplazÃ³ a Ã©ste en una rotaciÃ³n. Permite trazar la cadena de refresh.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'id_refresh_token_reemplazo';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.refresh_token')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.refresh_token'),N'ip_creacion',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'IP de origen donde se emitiÃ³ el token (IPv4 o IPv6). Para auditorÃ­a de sesiones.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'ip_creacion';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'IP de origen donde se emitiÃ³ el token (IPv4 o IPv6). Para auditorÃ­a de sesiones.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'ip_creacion';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.refresh_token')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.refresh_token'),N'user_agent',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'User-Agent del cliente que emitiÃ³ el token. Para auditorÃ­a de sesiones.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'user_agent';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'User-Agent del cliente que emitiÃ³ el token. Para auditorÃ­a de sesiones.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'refresh_token',
 @level2type=N'COLUMN', @level2name=N'user_agent';


-- ----- Tabla: usuario_perfil -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario_perfil') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'AsignaciÃ³n N:M entre usuarios y perfiles. PK compuesta sin generated by default as identity.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario_perfil';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'AsignaciÃ³n N:M entre usuarios y perfiles. PK compuesta sin generated by default as identity.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario_perfil';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario_perfil')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario_perfil'),N'id_usuario',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'FK al usuario. Parte de la PK compuesta.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario_perfil',
 @level2type=N'COLUMN', @level2name=N'id_usuario';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK al usuario. Parte de la PK compuesta.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario_perfil',
 @level2type=N'COLUMN', @level2name=N'id_usuario';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.usuario_perfil')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.usuario_perfil'),N'id_perfil',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'FK al perfil. Parte de la PK compuesta.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario_perfil',
 @level2type=N'COLUMN', @level2name=N'id_perfil';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK al perfil. Parte de la PK compuesta.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'usuario_perfil',
 @level2type=N'COLUMN', @level2name=N'id_perfil';


-- ----- Tabla: perfil_rol -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil_rol') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'AsignaciÃ³n de un rol a un perfil con un nivel de seguridad especÃ­fico. El claim_code es el identificador estable que viaja en el JWT.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'AsignaciÃ³n de un rol a un perfil con un nivel de seguridad especÃ­fico. El claim_code es el identificador estable que viaja en el JWT.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil_rol')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil_rol'),N'id_perfil_rol',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico de la asignaciÃ³n. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol',
 @level2type=N'COLUMN', @level2name=N'id_perfil_rol';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico de la asignaciÃ³n. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol',
 @level2type=N'COLUMN', @level2name=N'id_perfil_rol';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil_rol')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil_rol'),N'id_perfil',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'FK al perfil.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol',
 @level2type=N'COLUMN', @level2name=N'id_perfil';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK al perfil.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol',
 @level2type=N'COLUMN', @level2name=N'id_perfil';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil_rol')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil_rol'),N'id_rol',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'FK al rol.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol',
 @level2type=N'COLUMN', @level2name=N'id_rol';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK al rol.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol',
 @level2type=N'COLUMN', @level2name=N'id_rol';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil_rol')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil_rol'),N'id_nivel_seguridad',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'FK al nivel de seguridad con que se asigna el rol al perfil.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol',
 @level2type=N'COLUMN', @level2name=N'id_nivel_seguridad';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK al nivel de seguridad con que se asigna el rol al perfil.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol',
 @level2type=N'COLUMN', @level2name=N'id_nivel_seguridad';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil_rol')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil_rol'),N'claim_code',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Identificador estable que viaja en el JWT (ej. DET_NIVEL_2). Ãšnico.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol',
 @level2type=N'COLUMN', @level2name=N'claim_code';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador estable que viaja en el JWT (ej. DET_NIVEL_2). Ãšnico.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol',
 @level2type=N'COLUMN', @level2name=N'claim_code';


-- ----- Tabla: perfil_rol_permiso -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil_rol_permiso') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'AsignaciÃ³n de permisos a la combinaciÃ³n perfil-rol-nivel. Es la tabla que finalmente determina quÃ© puede hacer un usuario en el sistema.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol_permiso';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'AsignaciÃ³n de permisos a la combinaciÃ³n perfil-rol-nivel. Es la tabla que finalmente determina quÃ© puede hacer un usuario en el sistema.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol_permiso';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil_rol_permiso')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil_rol_permiso'),N'id_perfil_rol_permiso',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico de la asignaciÃ³n. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol_permiso',
 @level2type=N'COLUMN', @level2name=N'id_perfil_rol_permiso';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico de la asignaciÃ³n. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol_permiso',
 @level2type=N'COLUMN', @level2name=N'id_perfil_rol_permiso';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil_rol_permiso')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil_rol_permiso'),N'id_perfil_rol',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'FK a perfil_rol (combinaciÃ³n perfil-rol-nivel).',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol_permiso',
 @level2type=N'COLUMN', @level2name=N'id_perfil_rol';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a perfil_rol (combinaciÃ³n perfil-rol-nivel).',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol_permiso',
 @level2type=N'COLUMN', @level2name=N'id_perfil_rol';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.perfil_rol_permiso')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.perfil_rol_permiso'),N'id_permiso',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'FK al permiso otorgado.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol_permiso',
 @level2type=N'COLUMN', @level2name=N'id_permiso';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK al permiso otorgado.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'perfil_rol_permiso',
 @level2type=N'COLUMN', @level2name=N'id_permiso';


-- ----- Tabla: parametro -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.parametro') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'ConfiguraciÃ³n global del sistema de autenticaciÃ³n. PatrÃ³n key-value con tipado fuerte: cada parÃ¡metro tiene un nombre Ãºnico (ej. login.intentos_maximos) y se almacena en la columna que corresponde a su tipo (valor_numerico o valor_varchar). El CHECK ck_parametro_tipo_valor garantiza coherencia tipo-valor.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'ConfiguraciÃ³n global del sistema de autenticaciÃ³n. PatrÃ³n key-value con tipado fuerte: cada parÃ¡metro tiene un nombre Ãºnico (ej. login.intentos_maximos) y se almacena en la columna que corresponde a su tipo (valor_numerico o valor_varchar). El CHECK ck_parametro_tipo_valor garantiza coherencia tipo-valor.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.parametro')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.parametro'),N'id_parametro',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del parÃ¡metro. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'id_parametro';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del parÃ¡metro. Clave primaria autoincremental.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'id_parametro';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.parametro')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.parametro'),N'nombre_parametro',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Nombre Ãºnico del parÃ¡metro en formato namespace.nombre (ej. login.intentos_maximos, login.tiempo_espera_seg, login.reintentos_activado). Es el identificador estable que la aplicaciÃ³n consulta.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'nombre_parametro';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Nombre Ãºnico del parÃ¡metro en formato namespace.nombre (ej. login.intentos_maximos, login.tiempo_espera_seg, login.reintentos_activado). Es el identificador estable que la aplicaciÃ³n consulta.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'nombre_parametro';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.parametro')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.parametro'),N'tipo_dato',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Discriminador que indica quÃ© columna contiene el valor. Valores permitidos: NUMERICO (valor_numerico), VARCHAR (valor_varchar), BOOLEAN (valor_numerico restringido a 0/1).',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'tipo_dato';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Discriminador que indica quÃ© columna contiene el valor. Valores permitidos: NUMERICO (valor_numerico), VARCHAR (valor_varchar), BOOLEAN (valor_numerico restringido a 0/1).',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'tipo_dato';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.parametro')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.parametro'),N'valor_numerico',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Valor del parÃ¡metro cuando tipo_dato es NUMERICO o BOOLEAN. NULL si tipo_dato es VARCHAR.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'valor_numerico';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Valor del parÃ¡metro cuando tipo_dato es NUMERICO o BOOLEAN. NULL si tipo_dato es VARCHAR.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'valor_numerico';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.parametro')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.parametro'),N'valor_varchar',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Valor del parÃ¡metro cuando tipo_dato es VARCHAR. NULL si tipo_dato es NUMERICO o BOOLEAN.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'valor_varchar';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Valor del parÃ¡metro cuando tipo_dato es VARCHAR. NULL si tipo_dato es NUMERICO o BOOLEAN.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'valor_varchar';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.parametro')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.parametro'),N'activo',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Indica si el parÃ¡metro estÃ¡ vigente (1) o desactivado (0). Permite deshabilitar parÃ¡metros sin perder su valor histÃ³rico. Default 1.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'activo';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Indica si el parÃ¡metro estÃ¡ vigente (1) o desactivado (0). Permite deshabilitar parÃ¡metros sin perder su valor histÃ³rico. Default 1.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'activo';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('auth.parametro')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('auth.parametro'),N'descripcion',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'DescripciÃ³n humana del parÃ¡metro para la UI de administraciÃ³n. Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'descripcion';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'DescripciÃ³n humana del parÃ¡metro para la UI de administraciÃ³n. Opcional.',
 @level0type=N'SCHEMA', @level0name=N'auth', @level1type=N'TABLE', @level1name=N'parametro',
 @level2type=N'COLUMN', @level2name=N'descripcion';


-- =============================================================================
-- FIN â€” V0002__nuevo_esquema_auth
-- =============================================================================
-- ValidaciÃ³n recomendada (despuÃ©s de ejecutar):
-- SELECT COUNT(*) FROM sys.tables
-- WHERE schema_id = SCHEMA_ID('auth'); -- esperado: 10
-- SELECT COUNT(*) FROM sys.foreign_keys fk
-- JOIN sys.tables t ON fk.parent_object_id = t.object_id
-- WHERE t.schema_id = SCHEMA_ID('auth'); -- esperado: 10
-- SELECT COUNT(*) FROM sys.indexes i
-- JOIN sys.tables t ON i.object_id = t.object_id
-- WHERE t.schema_id = SCHEMA_ID('auth')
-- AND i.is_primary_key = 0 AND i.is_unique_constraint = 0
-- AND i.type_desc = 'NONCLUSTERED'; -- esperado: 3
-- SELECT COUNT(*) FROM sys.extended_properties ep
-- JOIN sys.objects o ON ep.major_id = o.object_id
-- WHERE ep.name = 'MS_Description'
-- AND o.schema_id = SCHEMA_ID('auth'); -- esperado: ~54
-- =============================================================================

