-- =============================================================================
-- SIP â€” Migration V0007__catalogos_estado_denuncia
-- =============================================================================
-- VersiÃ³n: 4.0 v6 (incremental sobre V0006)
-- Compatible: SQL Server 2017+ (forward-compatible 2022)
-- Depende de: V0001__baseline_sip.sql (define denuncias.denuncia)
-- V0006__realojamiento_catalogos.sql (estado vivo previo)
--
-- ALCANCE:
-- 1. Crea dos catÃ¡logos nuevos en el esquema denuncias para soportar las
-- mÃ¡quinas de estado del proceso PO01.01 v2.0.0 (GestiÃ³n de Denuncias):
-- - denuncias.cat_estado_denuncia (7 valores)
-- - denuncias.cat_estado_envio_fiscalia (3 valores)
--
-- 2. Reemplaza las columnas varchar(20) de denuncias.denuncia por
-- claves forÃ¡neas a los nuevos catÃ¡logos:
-- - estado_denuncia (NVARCHAR) â†’ id_estado_denuncia (INTEGER FK)
-- - estado_envio_fiscalia (NVARCHAR) â†’ id_estado_envio_fiscalia (INTEGER FK)
--
-- 3. Elimina la columna redundante estado_borrador. Sus valores
-- (BORRADOR/COMPLETA/VISADA) duplicaban funcionalidad de estado_denuncia
-- con un dominio menos completo que el del proceso PO01.01 v2.0.0.
--
-- 4. Repara el bug detectado en denuncias.procedimiento_policial:
-- la FK fk_proc_programa estaba duplicada apuntando a dos tablas
-- distintas (residuo del realojamiento del V0006 de cat_programa_seguridad
-- desde casos a configuracion).
--
-- 5. Actualiza descripciones extendidas de las columnas afectadas.
--
-- JUSTIFICACIÃ“N (resumen):
-- El esquema denuncias mantenÃ­a 3 columnas de estado como varchar(20) sin
-- catÃ¡logo respaldado por FK ni CHECK constraint, contraviniendo el patrÃ³n
-- aplicado en otros esquemas operativos del modelo (casos.cat_estado_caso,
-- diligencias.cat_estado_diligencia, evidencias.cat_estado_especie). El
-- anÃ¡lisis del proceso PO01.01 v2.0.0 (BPMN + documento de proceso) confirmÃ³
-- que estas columnas representan mÃ¡quinas de estado con dominios cerrados
-- que requieren catÃ¡logo institucional.
--
-- Detalle del anÃ¡lisis comparativo: ver documento "Hallazgos del Modelo SIP
-- vs Proceso PO01.01 - GestiÃ³n de Denuncias".
--
-- DATOS PRODUCTIVOS:
-- Esta migration aplica sobre una base nueva sin datos productivos. Por
-- esto NO se incluyen bloques de migraciÃ³n de datos. Los catÃ¡logos quedan
-- vacÃ­os al tÃ©rmino de V0007 â€” los datos semilla se cargan mediante el
-- script repetible R__denuncias_seed.sql.
--
-- ORDEN DE EJECUCIÃ“N:
-- V0007 (este script, estructural) DEBE ejecutarse antes de R__denuncias_seed.
-- Flyway garantiza este orden: las versionadas se aplican en orden de versiÃ³n,
-- las repetibles se aplican al final del bucle de versionadas y se reaplican
-- cada vez que su contenido cambia.
--
-- IDEMPOTENCIA:
-- Se aplican guardas IF EXISTS / IF NOT EXISTS donde corresponde para que
-- la migration sea segura ante reaplicaciÃ³n parcial (ej: drop accidental +
-- restore + re-migrate).
--
-- ROLLBACK:
-- No hay rollback automÃ¡tico en Flyway para Versioned migrations. Si se
-- requiere revertir, debe restaurarse desde backup. Como esta migration
-- aplica sobre base nueva sin datos, el rollback equivale a recrear desde
-- V0001 hasta V0006.
-- =============================================================================
SET ANSI_NULLS ON;
SET ANSI_WARNINGS ON;
SET ANSI_PADDING ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;


-- =============================================================================
-- BLOQUE 1 â€” CREAR CATÃLOGOS NUEVOS
-- =============================================================================
-- Sigue el patrÃ³n de catÃ¡logos del modelo: id generated by default as identity, codigo Ãºnico,
-- nombre descriptivo, es_terminal para reporterÃ­a, orden para presentaciÃ³n,
-- activo para baja lÃ³gica. CHECK constraints sobre los SMALLINT booleanos.
-- =============================================================================

-- â”€â”€â”€ denuncias.cat_estado_denuncia â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF OBJECT_ID('denuncias.cat_estado_denuncia', 'U') IS NULL
BEGIN
 CREATE TABLE denuncias.cat_estado_denuncia (
 id_estado_denuncia INTEGER NOT NULL generated by default as generated by default as identity,
 codigo varchar(30) NOT NULL,
 nombre varchar(80) NOT NULL,
 es_terminal SMALLINT NOT NULL DEFAULT 0,
 orden INTEGER NULL,
 activo SMALLINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_cat_estado_denuncia
 PRIMARY KEY (id_estado_denuncia),
 CONSTRAINT uq_cat_estado_denuncia_codigo
 UNIQUE (codigo),
 CONSTRAINT ck_cat_estado_denuncia_es_terminal
 CHECK (es_terminal IN (0,1)),
 CONSTRAINT ck_cat_estado_denuncia_activo
 CHECK (activo IN (0,1))
 );
END;

-- â”€â”€â”€ denuncias.cat_estado_envio_fiscalia â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF OBJECT_ID('denuncias.cat_estado_envio_fiscalia', 'U') IS NULL
BEGIN
 CREATE TABLE denuncias.cat_estado_envio_fiscalia (
 id_estado_envio_fiscalia INTEGER NOT NULL generated by default as generated by default as identity,
 codigo varchar(30) NOT NULL,
 nombre varchar(80) NOT NULL,
 es_terminal SMALLINT NOT NULL DEFAULT 0,
 orden INTEGER NULL,
 activo SMALLINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_cat_estado_envio_fiscalia
 PRIMARY KEY (id_estado_envio_fiscalia),
 CONSTRAINT uq_cat_estado_envio_fiscalia_codigo
 UNIQUE (codigo),
 CONSTRAINT ck_cat_estado_envio_fiscalia_es_terminal
 CHECK (es_terminal IN (0,1)),
 CONSTRAINT ck_cat_estado_envio_fiscalia_activo
 CHECK (activo IN (0,1))
 );
END;


-- =============================================================================
-- BLOQUE 2 â€” DESCRIPCIONES EXTENDIDAS DE LOS CATÃLOGOS NUEVOS
-- =============================================================================

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_denuncia')
 AND minor_id = 0
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'CatÃ¡logo de estados de la denuncia en su ciclo de vida operativo. Refleja la mÃ¡quina de estados del proceso PO01.01 v2.0.0 (GestiÃ³n de Denuncias) mÃ¡s el estado terminal ANULADA. Los estados terminales (es_terminal = 1) cierran el ciclo de vida.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'CatÃ¡logo de estados de la denuncia en su ciclo de vida operativo. Refleja la mÃ¡quina de estados del proceso PO01.01 v2.0.0 (GestiÃ³n de Denuncias) mÃ¡s el estado terminal ANULADA. Los estados terminales (es_terminal = 1) cierran el ciclo de vida.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_denuncia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.cat_estado_denuncia'), 'id_estado_denuncia', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'Identificador Ãºnico del estado de denuncia. Clave primaria autogenerada por el motor.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia',
 @level2type = N'COLUMN', @level2name = N'id_estado_denuncia';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Identificador Ãºnico del estado de denuncia. Clave primaria autogenerada por el motor.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia',
 @level2type = N'COLUMN', @level2name = N'id_estado_denuncia';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_denuncia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.cat_estado_denuncia'), 'codigo', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'CÃ³digo abreviado del estado, en mayÃºsculas con guion bajo. Inmutable una vez creado el catÃ¡logo. Ej: BORRADOR, FIRMADA_POR_JEFATURA, NOTIFICADA_FISCALIA.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia',
 @level2type = N'COLUMN', @level2name = N'codigo';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'CÃ³digo abreviado del estado, en mayÃºsculas con guion bajo. Inmutable una vez creado el catÃ¡logo. Ej: BORRADOR, FIRMADA_POR_JEFATURA, NOTIFICADA_FISCALIA.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia',
 @level2type = N'COLUMN', @level2name = N'codigo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_denuncia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.cat_estado_denuncia'), 'nombre', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'Nombre descriptivo del estado para presentaciÃ³n en interfaces y reportes.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia',
 @level2type = N'COLUMN', @level2name = N'nombre';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Nombre descriptivo del estado para presentaciÃ³n en interfaces y reportes.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia',
 @level2type = N'COLUMN', @level2name = N'nombre';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_denuncia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.cat_estado_denuncia'), 'es_terminal', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'Indica si el estado cierra el ciclo de vida de la denuncia. 1 = terminal (NOTIFICADA_FISCALIA, ANULADA), 0 = transitorio.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia',
 @level2type = N'COLUMN', @level2name = N'es_terminal';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Indica si el estado cierra el ciclo de vida de la denuncia. 1 = terminal (NOTIFICADA_FISCALIA, ANULADA), 0 = transitorio.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia',
 @level2type = N'COLUMN', @level2name = N'es_terminal';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_denuncia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.cat_estado_denuncia'), 'orden', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'Orden numÃ©rico de presentaciÃ³n del estado en interfaces y reportes. Refleja la secuencia natural de la mÃ¡quina de estados.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia',
 @level2type = N'COLUMN', @level2name = N'orden';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Orden numÃ©rico de presentaciÃ³n del estado en interfaces y reportes. Refleja la secuencia natural de la mÃ¡quina de estados.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia',
 @level2type = N'COLUMN', @level2name = N'orden';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_denuncia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.cat_estado_denuncia'), 'activo', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'Indicador lÃ³gico de actividad del estado. 1 = activo (admitido para nuevas denuncias), 0 = inactivo (preserva trazabilidad histÃ³rica pero no admite nuevas asignaciones).',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia',
 @level2type = N'COLUMN', @level2name = N'activo';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Indicador lÃ³gico de actividad del estado. 1 = activo (admitido para nuevas denuncias), 0 = inactivo (preserva trazabilidad histÃ³rica pero no admite nuevas asignaciones).',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_denuncia',
 @level2type = N'COLUMN', @level2name = N'activo';

-- â”€â”€â”€ cat_estado_envio_fiscalia â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_envio_fiscalia')
 AND minor_id = 0
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'CatÃ¡logo de estados del subflujo de envÃ­o de la denuncia al Ministerio PÃºblico. Refleja la integraciÃ³n con la API de BitÃ¡cora Web de FiscalÃ­a documentada en PO01.01.04 Notificar FiscalÃ­a.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'CatÃ¡logo de estados del subflujo de envÃ­o de la denuncia al Ministerio PÃºblico. Refleja la integraciÃ³n con la API de BitÃ¡cora Web de FiscalÃ­a documentada en PO01.01.04 Notificar FiscalÃ­a.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_envio_fiscalia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.cat_estado_envio_fiscalia'), 'id_estado_envio_fiscalia', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'Identificador Ãºnico del estado de envÃ­o a FiscalÃ­a. Clave primaria autogenerada por el motor.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia',
 @level2type = N'COLUMN', @level2name = N'id_estado_envio_fiscalia';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Identificador Ãºnico del estado de envÃ­o a FiscalÃ­a. Clave primaria autogenerada por el motor.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia',
 @level2type = N'COLUMN', @level2name = N'id_estado_envio_fiscalia';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_envio_fiscalia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.cat_estado_envio_fiscalia'), 'codigo', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'CÃ³digo abreviado del estado, en mayÃºsculas. Inmutable una vez creado el catÃ¡logo. Ej: PENDIENTE, ENVIADO, PRORROGADO.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia',
 @level2type = N'COLUMN', @level2name = N'codigo';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'CÃ³digo abreviado del estado, en mayÃºsculas. Inmutable una vez creado el catÃ¡logo. Ej: PENDIENTE, ENVIADO, PRORROGADO.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia',
 @level2type = N'COLUMN', @level2name = N'codigo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_envio_fiscalia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.cat_estado_envio_fiscalia'), 'nombre', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'Nombre descriptivo del estado para presentaciÃ³n en interfaces y reportes.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia',
 @level2type = N'COLUMN', @level2name = N'nombre';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Nombre descriptivo del estado para presentaciÃ³n en interfaces y reportes.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia',
 @level2type = N'COLUMN', @level2name = N'nombre';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_envio_fiscalia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.cat_estado_envio_fiscalia'), 'es_terminal', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'Indica si el estado cierra el subflujo de envÃ­o. Bajo el modelo actual, ningÃºn estado se considera terminal estructuralmente: el cierre exitoso se infiere por la presencia del RUC en denuncia.folio_externo.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia',
 @level2type = N'COLUMN', @level2name = N'es_terminal';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Indica si el estado cierra el subflujo de envÃ­o. Bajo el modelo actual, ningÃºn estado se considera terminal estructuralmente: el cierre exitoso se infiere por la presencia del RUC en denuncia.folio_externo.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia',
 @level2type = N'COLUMN', @level2name = N'es_terminal';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_envio_fiscalia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.cat_estado_envio_fiscalia'), 'orden', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'Orden numÃ©rico de presentaciÃ³n del estado en interfaces y reportes.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia',
 @level2type = N'COLUMN', @level2name = N'orden';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Orden numÃ©rico de presentaciÃ³n del estado en interfaces y reportes.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia',
 @level2type = N'COLUMN', @level2name = N'orden';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.cat_estado_envio_fiscalia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.cat_estado_envio_fiscalia'), 'activo', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'Indicador lÃ³gico de actividad del estado. 1 = activo, 0 = inactivo.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia',
 @level2type = N'COLUMN', @level2name = N'activo';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Indicador lÃ³gico de actividad del estado. 1 = activo, 0 = inactivo.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'cat_estado_envio_fiscalia',
 @level2type = N'COLUMN', @level2name = N'activo';


-- =============================================================================
-- BLOQUE 3 â€” REEMPLAZAR COLUMNAS DE ESTADO EN denuncias.denuncia
-- =============================================================================
-- Como no hay datos productivos, se realiza el cambio limpio:
-- 1. Drop del Ã­ndice ix_denuncia_estado (referencia la columna antigua).
-- 2. Drop de las 3 columnas de estado.
-- 3. Add de las 2 columnas FK nuevas.
-- 4. Add de las constraints FK.
-- 5. Recrear el Ã­ndice ix_denuncia_estado sobre la columna FK nueva.
-- 6. Crear Ã­ndice adicional para consultas operativas de envÃ­o a fiscalÃ­a.
-- =============================================================================

-- 3.1 â€” Drop del Ã­ndice antes de poder dropear la columna
IF EXISTS (SELECT 1 FROM sys.indexes
 WHERE name = 'ix_denuncia_estado'
 AND object_id = OBJECT_ID('denuncias.denuncia'))
BEGIN
 DROP INDEX ix_denuncia_estado ON denuncias.denuncia;
END;

-- 3.2 â€” Drop dinÃ¡mico de DEFAULT constraints autogenerados
-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
-- Las columnas estado_denuncia, estado_envio_fiscalia y estado_borrador
-- fueron declaradas en V0001 con DEFAULT inline sin nombre explÃ­cito de
-- constraint. SQL Server les asignÃ³ nombres autogenerados con sufijo
-- aleatorio (DF__denuncia__estado__XXXXXXXX) que VARÃAN entre ambientes.
-- Para poder dropear las columnas, hay que eliminar primero los DEFAULT
-- constraints asociados, descubriendo sus nombres dinÃ¡micamente vÃ­a
-- sys.default_constraints + sys.columns.
-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
DECLARE @drop_default_sql text = N'';

SELECT @drop_default_sql = @drop_default_sql
 + N'ALTER TABLE denuncias.denuncia DROP CONSTRAINT '
 + dc.name + N';' + CHAR(13) + CHAR(10)
 FROM sys.default_constraints dc
 JOIN sys.columns c
 ON c.object_id = dc.parent_object_id
 AND c.column_id = dc.parent_column_id
 WHERE dc.parent_object_id = OBJECT_ID('denuncias.denuncia')
 AND c.name IN (N'estado_denuncia', N'estado_envio_fiscalia', N'estado_borrador');

IF LEN(@drop_default_sql) > 0
BEGIN
 PRINT N'V0007 - Eliminando DEFAULT constraints autogenerados:';
 PRINT @drop_default_sql;
 EXEC sp_executesql @drop_default_sql;
END;

-- 3.3 â€” Drop de las 3 columnas de estado
-- Nota: estado_borrador se elimina sin reemplazo (era redundante con estado_denuncia)
IF COL_LENGTH('denuncias.denuncia', 'estado_denuncia') IS NOT NULL
 ALTER TABLE denuncias.denuncia DROP COLUMN estado_denuncia;

IF COL_LENGTH('denuncias.denuncia', 'estado_envio_fiscalia') IS NOT NULL
 ALTER TABLE denuncias.denuncia DROP COLUMN estado_envio_fiscalia;

IF COL_LENGTH('denuncias.denuncia', 'estado_borrador') IS NOT NULL
 ALTER TABLE denuncias.denuncia DROP COLUMN estado_borrador;

-- 3.4 â€” Add columnas FK nuevas
-- id_estado_denuncia: NOT NULL (toda denuncia tiene siempre un estado)
-- id_estado_envio_fiscalia: NULL (solo aplica desde que la denuncia entra al
-- subflujo de envÃ­o, post-firma de jefatura)
IF COL_LENGTH('denuncias.denuncia', 'id_estado_denuncia') IS NULL
 ALTER TABLE denuncias.denuncia
 ADD id_estado_denuncia INTEGER NOT NULL
 CONSTRAINT df_denuncia_estado DEFAULT (1); -- 1 = BORRADOR (semilla R__)

IF COL_LENGTH('denuncias.denuncia', 'id_estado_envio_fiscalia') IS NULL
 ALTER TABLE denuncias.denuncia
 ADD id_estado_envio_fiscalia INTEGER NULL;

-- 3.5 â€” Add constraints FK
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys
 WHERE name = 'fk_denuncia_estado_denuncia'
 AND parent_object_id = OBJECT_ID('denuncias.denuncia'))
BEGIN
 ALTER TABLE denuncias.denuncia
 ADD CONSTRAINT fk_denuncia_estado_denuncia
 FOREIGN KEY (id_estado_denuncia)
 REFERENCES denuncias.cat_estado_denuncia (id_estado_denuncia);
END;

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys
 WHERE name = 'fk_denuncia_estado_envio_fiscalia'
 AND parent_object_id = OBJECT_ID('denuncias.denuncia'))
BEGIN
 ALTER TABLE denuncias.denuncia
 ADD CONSTRAINT fk_denuncia_estado_envio_fiscalia
 FOREIGN KEY (id_estado_envio_fiscalia)
 REFERENCES denuncias.cat_estado_envio_fiscalia (id_estado_envio_fiscalia);
END;

-- 3.6 â€” Recrear Ã­ndice operativo (ahora sobre la columna FK nueva)
IF NOT EXISTS (SELECT 1 FROM sys.indexes
 WHERE name = 'ix_denuncia_estado'
 AND object_id = OBJECT_ID('denuncias.denuncia'))
BEGIN
 CREATE INDEX ix_denuncia_estado
 ON denuncias.denuncia (id_estado_denuncia, fecha_denuncia);
END;

-- 3.7 â€” Ãndice adicional para consultas operativas de envÃ­o a fiscalÃ­a
-- (filtered index: solo registros con envÃ­o iniciado)
IF NOT EXISTS (SELECT 1 FROM sys.indexes
 WHERE name = 'ix_denuncia_envio_fiscalia'
 AND object_id = OBJECT_ID('denuncias.denuncia'))
BEGIN
 CREATE INDEX ix_denuncia_envio_fiscalia
 ON denuncias.denuncia (id_estado_envio_fiscalia)
 WHERE id_estado_envio_fiscalia IS NOT NULL;
END;


-- =============================================================================
-- BLOQUE 4 â€” DESCRIPCIONES EXTENDIDAS DE LAS COLUMNAS NUEVAS
-- =============================================================================

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.denuncia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.denuncia'), 'id_estado_denuncia', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'Estado actual de la denuncia en su ciclo de vida operativo. FK a denuncias.cat_estado_denuncia. La mÃ¡quina de estados sigue el proceso PO01.01 v2.0.0: BORRADOR â†’ FIRMADA_POR_INVESTIGADOR â†’ EN_REVISION â†’ (OBSERVADO â†” EN_REVISION) â†’ FIRMADA_POR_JEFATURA â†’ NOTIFICADA_FISCALIA. El estado terminal alternativo ANULADA admite ingreso desde estados no terminales. La validaciÃ³n de transiciones permitidas es responsabilidad de la capa de aplicaciÃ³n.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'denuncia',
 @level2type = N'COLUMN', @level2name = N'id_estado_denuncia';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Estado actual de la denuncia en su ciclo de vida operativo. FK a denuncias.cat_estado_denuncia. La mÃ¡quina de estados sigue el proceso PO01.01 v2.0.0: BORRADOR â†’ FIRMADA_POR_INVESTIGADOR â†’ EN_REVISION â†’ (OBSERVADO â†” EN_REVISION) â†’ FIRMADA_POR_JEFATURA â†’ NOTIFICADA_FISCALIA. El estado terminal alternativo ANULADA admite ingreso desde estados no terminales. La validaciÃ³n de transiciones permitidas es responsabilidad de la capa de aplicaciÃ³n.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'denuncia',
 @level2type = N'COLUMN', @level2name = N'id_estado_denuncia';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties
 WHERE class = 1
 AND major_id = OBJECT_ID('denuncias.denuncia')
 AND minor_id = COLUMNPROPERTY(OBJECT_ID('denuncias.denuncia'), 'id_estado_envio_fiscalia', 'ColumnId')
 AND name = N'MS_Description'
)
 EXEC sys.sp_updateextendedproperty
 @name = N'MS_Description',
 @value = N'Estado del subflujo de envÃ­o de la denuncia a FiscalÃ­a. FK a denuncias.cat_estado_envio_fiscalia. Es NULL hasta que la denuncia entra al subflujo de envÃ­o (tras FIRMADA_POR_JEFATURA). Valores: PENDIENTE â†’ ENVIADO â†’ PRORROGADO. El cierre exitoso del envÃ­o se infiere por la presencia del RUC en denuncia.folio_externo. Documentado en proceso PO01.01.04 Notificar FiscalÃ­a.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'denuncia',
 @level2type = N'COLUMN', @level2name = N'id_estado_envio_fiscalia';
ELSE
 EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Estado del subflujo de envÃ­o de la denuncia a FiscalÃ­a. FK a denuncias.cat_estado_envio_fiscalia. Es NULL hasta que la denuncia entra al subflujo de envÃ­o (tras FIRMADA_POR_JEFATURA). Valores: PENDIENTE â†’ ENVIADO â†’ PRORROGADO. El cierre exitoso del envÃ­o se infiere por la presencia del RUC en denuncia.folio_externo. Documentado en proceso PO01.01.04 Notificar FiscalÃ­a.',
 @level0type = N'SCHEMA', @level0name = N'denuncias',
 @level1type = N'TABLE', @level1name = N'denuncia',
 @level2type = N'COLUMN', @level2name = N'id_estado_envio_fiscalia';


-- =============================================================================
-- BLOQUE 5 â€” REPARAR BUG DE FK DUPLICADA EN procedimiento_policial
-- =============================================================================
-- El V0006 (realojamiento de cat_programa_seguridad de casos a configuracion)
-- dejÃ³ dos FKs con el mismo nombre fk_proc_programa apuntando a tablas
-- distintas:
-- - fk_proc_programa: id_programa_seguridad â†’ casos.cat_programa_seguridad
-- - fk_proc_programa: id_programa_seguridad â†’ configuracion.cat_programa_seguridad
--
-- Esto puede generar comportamiento ambiguo. La FK correcta es la que apunta
-- a configuracion (destino del realojamiento). Se elimina la FK obsoleta
-- (la que apunta a casos) y se mantiene Ãºnicamente la nueva, renombrÃ¡ndola
-- para mayor claridad si es necesario.
-- =============================================================================

-- DiagnÃ³stico: listar FKs actuales sobre procedimiento_policial.id_programa_seguridad
-- (informativo en logs de ejecuciÃ³n)
DECLARE @fk_obsoleta_id INT;

SELECT @fk_obsoleta_id = fk.object_id
 FROM sys.foreign_keys fk
 JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id
 JOIN sys.columns c ON c.object_id = fkc.parent_object_id 
 AND c.column_id = fkc.parent_column_id
 WHERE fk.parent_object_id = OBJECT_ID('denuncias.procedimiento_policial')
 AND c.name = 'id_programa_seguridad'
 AND fk.referenced_object_id = OBJECT_ID('casos.cat_programa_seguridad');

IF @fk_obsoleta_id IS NOT NULL
BEGIN
 DECLARE @fk_obsoleta_nombre varchar(128);
 SELECT @fk_obsoleta_nombre = name FROM sys.foreign_keys WHERE object_id = @fk_obsoleta_id;
 DECLARE @sql varchar(500) = 
 N'ALTER TABLE denuncias.procedimiento_policial DROP CONSTRAINT ' 
 + @fk_obsoleta_nombre + N'';
 EXEC sp_executesql @sql;
END;


-- =============================================================================
-- FIN â€” V0007__catalogos_estado_denuncia
-- =============================================================================
-- ValidaciÃ³n recomendada (despuÃ©s de ejecutar):
--
-- -- CatÃ¡logos creados
-- SELECT name FROM sys.tables
-- WHERE schema_id = SCHEMA_ID('denuncias')
-- AND name IN ('cat_estado_denuncia', 'cat_estado_envio_fiscalia');
-- -- esperado: 2 filas
--
-- -- CatÃ¡logos vacÃ­os (los datos los carga R__denuncias_seed.sql)
-- SELECT COUNT(*) FROM denuncias.cat_estado_denuncia;
-- SELECT COUNT(*) FROM denuncias.cat_estado_envio_fiscalia;
-- -- esperado: 0 filas en cada uno (hasta que corra R__denuncias_seed)
--
-- -- Columnas nuevas en denuncia
-- SELECT name, system_type_id, is_nullable
-- FROM sys.columns
-- WHERE object_id = OBJECT_ID('denuncias.denuncia')
-- AND name IN ('id_estado_denuncia', 'id_estado_envio_fiscalia');
-- -- esperado: 2 filas con tipo INT (56)
--
-- -- Columnas viejas eliminadas
-- SELECT name FROM sys.columns
-- WHERE object_id = OBJECT_ID('denuncias.denuncia')
-- AND name IN ('estado_denuncia', 'estado_envio_fiscalia', 'estado_borrador');
-- -- esperado: 0 filas
--
-- -- FKs creadas
-- SELECT name FROM sys.foreign_keys
-- WHERE parent_object_id = OBJECT_ID('denuncias.denuncia')
-- AND name IN ('fk_denuncia_estado_denuncia', 'fk_denuncia_estado_envio_fiscalia');
-- -- esperado: 2 filas
--
-- -- FK obsoleta de procedimiento_policial eliminada
-- SELECT fk.name, OBJECT_NAME(fk.referenced_object_id) AS referenced_table
-- FROM sys.foreign_keys fk
-- WHERE fk.parent_object_id = OBJECT_ID('denuncias.procedimiento_policial')
-- AND fk.referenced_object_id = OBJECT_ID('casos.cat_programa_seguridad');
-- -- esperado: 0 filas
--
-- -- Verificar que el Ã­ndice operativo se recreÃ³ correctamente
-- SELECT i.name, c.name AS column_name
-- FROM sys.indexes i
-- JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id
-- JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
-- WHERE i.object_id = OBJECT_ID('denuncias.denuncia')
-- AND i.name IN ('ix_denuncia_estado', 'ix_denuncia_envio_fiscalia')
-- ORDER BY i.name, ic.key_ordinal;
-- -- esperado: 3 filas (ix_denuncia_estado x 2 columnas, ix_denuncia_envio_fiscalia x 1)
-- =============================================================================

