-- =============================================================================
-- SIP â€” Migration V0003__nuevo_esquema_encargos
-- =============================================================================
-- VersiÃ³n: 4.0 v3 (incremental sobre V0002)
-- Compatible: SQL Server 2017+ (forward-compatible 2022)
-- Depende de: V0001__baseline_sip.sql (esquemas personas, denuncias,
-- diligencias, tareas)
--
-- ALCANCE:
-- Crea el esquema `encargos` con el modelo de gestiÃ³n de encargos:
-- personas buscadas, Ã³rdenes judiciales del PJUD, presuntas desgracias,
-- y trazabilidad con denuncias, diligencias y tareas.
--
-- MAPEO CON MACROPROCESOS PDI:
-- - PO01 â€” InvestigaciÃ³n Criminal (encargos derivados de denuncias y diligencias)
-- - PO03 â€” CooperaciÃ³n Internacional (Ã³rdenes judiciales internacionales)
--
-- ESTRUCTURA DEL ARCHIVO:
-- PASO 1 â€” Esquema
-- PASO 2 â€” Tablas (sÃ³lo PK/UQ/CK; sin FKs)
-- PASO 3 â€” Ãndices
-- PASO 4 â€” Foreign keys internas (intra-esquema encargos)
-- PASO 5 â€” Foreign keys cruzadas (a otros esquemas)
-- PASO 6 â€” Descripciones (sys.sp_addextendedproperty idempotente)
--
-- CONVENCIONES APLICADAS (heredadas de V0001 y V0002):
-- - PKs nombradas id_<tabla> con generated by default as generated by default as identity cuando son locales
-- - INTEGER para todas las PKs y FKs (no BIGINT â€” consistente con baseline)
-- - NVARCHAR para texto con caracteres especiales (acentos, Ã±)
-- - timestamp para timestamps con CURRENT_TIMESTAMP (UTC)
-- - Naming lowercase con prefijos pk_/fk_/uq_/ix_/ck_
-- - Sin ON DELETE CASCADE (consistencia con V0001/V0002 â€” bloqueo intencional
-- para forzar limpieza explÃ­cita)
-- - Booleans como SMALLINT con CHECK IN (0,1) (no se usa boolean)
-- - Schema/tabla en brackets
-- - Sin comando USE (Flyway controla la conexiÃ³n vÃ­a URL JDBC)
--
-- TRADUCCIÃ“N APLICADA DESDE EL INPUT POSTGRESQL:
-- - BIGINT GENERATED ALWAYS AS generated by default as identity â†’ INTEGER generated by default as generated by default as identity
-- - BIGINT (FKs cruzadas) â†’ INTEGER (alineado con PKs target del baseline)
-- - TIMESTAMP DEFAULT CURRENT_TIMESTAMP â†’ timestamp DEFAULT CURRENT_TIMESTAMP
-- - VARCHAR â†’ varchar(texto con acentos)
-- - TEXT â†’ text
-- - COMMENT ON â†’ sys.sp_addextendedproperty
-- - ON DELETE CASCADE â†’ eliminado (consistencia)
--
-- DECISIONES DE DISEÃ‘O REGISTRADAS:
-- - Relaciones 1:1 estrictas (encargoâ†”denuncia, encargoâ†”diligencia,
-- tareaâ†”encargo) segÃºn diseÃ±o actual; pendiente revisiÃ³n con PDI si en
-- algÃºn caso se requiere N:M.
-- - id_orden_judicial con IDENTITY (id local del SIP, no externo PJUD).
-- - CatÃ¡logos tipo_encargo y tipo_orden_judicial con generated by default as identity tambiÃ©n
-- (id_local autogenerado), las filas se cargan vÃ­a R__ posterior.
-- =============================================================================
SET ANSI_NULLS ON;
SET ANSI_WARNINGS ON;
SET ANSI_PADDING ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;


-- =============================================================================
-- PASO 1 â€” ESQUEMA
-- =============================================================================

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'encargos')
 EXEC('CREATE SCHEMA encargos');


-- =============================================================================
-- PASO 2 â€” TABLAS
-- =============================================================================

-- Tabla: encargos.tipo_encargo
-- CatÃ¡logo de tipos de encargo: personas, armas, vehÃ­culos, otros.
CREATE TABLE encargos.tipo_encargo (
 id_tipo_encargo INTEGER generated by default as generated by default as identity NOT NULL,
 nombre varchar(200) NOT NULL,
 CONSTRAINT pk_tipo_encargo PRIMARY KEY (id_tipo_encargo),
 CONSTRAINT uq_tipo_encargo_nombre UNIQUE (nombre)
);


-- Tabla: encargos.tipo_orden_judicial
-- CatÃ¡logo de tipos de orden judicial provenientes del PJUD.
CREATE TABLE encargos.tipo_orden_judicial (
 id_tipo_orden_judicial INTEGER generated by default as generated by default as identity NOT NULL,
 nombre varchar(150) NOT NULL,
 CONSTRAINT pk_tipo_orden_judicial PRIMARY KEY (id_tipo_orden_judicial),
 CONSTRAINT uq_tipo_orden_judicial_nombre UNIQUE (nombre)
);


-- Tabla: encargos.encargo
-- Cabecera de todos los encargos del sistema con su vigencia.
CREATE TABLE encargos.encargo (
 id_encargo INTEGER generated by default as generated by default as identity NOT NULL,
 id_tipo_encargo INTEGER NOT NULL,
 fecha_inicio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 fecha_fin timestamp NULL,
 CONSTRAINT pk_encargo PRIMARY KEY (id_encargo),
 CONSTRAINT ck_encargo_fechas CHECK (
 fecha_fin IS NULL OR fecha_fin >= fecha_inicio
 )
);


-- Tabla: encargos.orden_judicial
-- Ã“rdenes judiciales provenientes del PJUD, asociables a encargos.
-- id_orden_judicial es local (SIP), no se respeta el id externo del PJUD.
CREATE TABLE encargos.orden_judicial (
 id_orden_judicial INTEGER generated by default as generated by default as identity NOT NULL,
 id_tipo_orden_judicial INTEGER NOT NULL,
 id_persona_buscada INTEGER NOT NULL,
 fecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 descripcion text NULL,
 CONSTRAINT pk_orden_judicial PRIMARY KEY (id_orden_judicial)
);


-- Tabla: encargos.encargo_denuncia
-- Asocia denuncia de presunta desgracia con su encargo (relaciÃ³n 1:1).
CREATE TABLE encargos.encargo_denuncia (
 id_encargo INTEGER NOT NULL,
 id_denuncia INTEGER NOT NULL,
 id_persona_buscada INTEGER NOT NULL,
 CONSTRAINT pk_encargo_denuncia PRIMARY KEY (id_encargo),
 CONSTRAINT uq_encargo_denuncia_denuncia UNIQUE (id_denuncia)
);


-- Tabla: encargos.encargo_orden_judicial
-- RelaciÃ³n N:M entre encargos y Ã³rdenes judiciales.
CREATE TABLE encargos.encargo_orden_judicial (
 id_encargo INTEGER NOT NULL,
 id_orden_judicial INTEGER NOT NULL,
 CONSTRAINT pk_encargo_orden_judicial PRIMARY KEY (id_encargo, id_orden_judicial)
);


-- Tabla: encargos.encargo_persona_diligencia
-- Asocia diligencia con encargo (relaciÃ³n 1:1, diligencia opcional).
CREATE TABLE encargos.encargo_persona_diligencia (
 id_encargo INTEGER NOT NULL,
 id_diligencia INTEGER NULL,
 id_persona_buscada INTEGER NOT NULL,
 CONSTRAINT pk_encargo_persona_diligencia PRIMARY KEY (id_encargo)
);


-- Tabla: encargos.tarea_encargo
-- Tareas que crean o gestionan encargos (relaciÃ³n 1:1: una tarea = un encargo).
-- id_tarea es INTEGER para coincidir con el tipo declarado en tareas.tarea.id_tarea
-- (INT generated by default as generated by default as identity). Mantener tipos coincidentes es requisito de SQL Server
-- para crear la FK fk_tarea_encargo_tarea (Msg 1778 si difieren).
CREATE TABLE encargos.tarea_encargo (
 id_tarea INTEGER NOT NULL,
 id_encargo INTEGER NOT NULL,
 CONSTRAINT pk_tarea_encargo PRIMARY KEY (id_tarea)
);


-- =============================================================================
-- PASO 3 â€” ÃNDICES
-- =============================================================================

CREATE INDEX ix_encargo_tipo
 ON encargos.encargo (id_tipo_encargo);

CREATE INDEX ix_encargo_vigencia
 ON encargos.encargo (fecha_inicio, fecha_fin);

CREATE INDEX ix_orden_judicial_tipo
 ON encargos.orden_judicial (id_tipo_orden_judicial);

CREATE INDEX ix_orden_judicial_persona
 ON encargos.orden_judicial (id_persona_buscada);

CREATE INDEX ix_encargo_denuncia_persona
 ON encargos.encargo_denuncia (id_persona_buscada);

CREATE INDEX ix_encargo_orden_judicial_oj
 ON encargos.encargo_orden_judicial (id_orden_judicial);

CREATE INDEX ix_encargo_persona_diligencia_persona
 ON encargos.encargo_persona_diligencia (id_persona_buscada);

CREATE INDEX ix_encargo_persona_diligencia_diligencia
 ON encargos.encargo_persona_diligencia (id_diligencia);

CREATE INDEX ix_tarea_encargo_encargo
 ON encargos.tarea_encargo (id_encargo);


-- =============================================================================
-- PASO 4 â€” FOREIGN KEYS INTERNAS (intra-esquema encargos)
-- =============================================================================

ALTER TABLE encargos.encargo
 ADD CONSTRAINT fk_encargo_tipo
 FOREIGN KEY (id_tipo_encargo)
 REFERENCES encargos.tipo_encargo (id_tipo_encargo);

ALTER TABLE encargos.orden_judicial
 ADD CONSTRAINT fk_orden_judicial_tipo
 FOREIGN KEY (id_tipo_orden_judicial)
 REFERENCES encargos.tipo_orden_judicial (id_tipo_orden_judicial);

ALTER TABLE encargos.encargo_denuncia
 ADD CONSTRAINT fk_encargo_denuncia_encargo
 FOREIGN KEY (id_encargo)
 REFERENCES encargos.encargo (id_encargo);

ALTER TABLE encargos.encargo_orden_judicial
 ADD CONSTRAINT fk_encargo_orden_judicial_encargo
 FOREIGN KEY (id_encargo)
 REFERENCES encargos.encargo (id_encargo);

ALTER TABLE encargos.encargo_orden_judicial
 ADD CONSTRAINT fk_encargo_orden_judicial_oj
 FOREIGN KEY (id_orden_judicial)
 REFERENCES encargos.orden_judicial (id_orden_judicial);

ALTER TABLE encargos.encargo_persona_diligencia
 ADD CONSTRAINT fk_encargo_persona_diligencia_encargo
 FOREIGN KEY (id_encargo)
 REFERENCES encargos.encargo (id_encargo);

ALTER TABLE encargos.tarea_encargo
 ADD CONSTRAINT fk_tarea_encargo_encargo
 FOREIGN KEY (id_encargo)
 REFERENCES encargos.encargo (id_encargo);


-- =============================================================================
-- PASO 5 â€” FOREIGN KEYS CRUZADAS (a otros esquemas)
-- =============================================================================

ALTER TABLE encargos.orden_judicial
 ADD CONSTRAINT fk_orden_judicial_persona
 FOREIGN KEY (id_persona_buscada)
 REFERENCES personas.persona (id_persona);

ALTER TABLE encargos.encargo_denuncia
 ADD CONSTRAINT fk_encargo_denuncia_denuncia
 FOREIGN KEY (id_denuncia)
 REFERENCES denuncias.denuncia (id_denuncia);

ALTER TABLE encargos.encargo_denuncia
 ADD CONSTRAINT fk_encargo_denuncia_persona
 FOREIGN KEY (id_persona_buscada)
 REFERENCES personas.persona (id_persona);

ALTER TABLE encargos.encargo_persona_diligencia
 ADD CONSTRAINT fk_encargo_persona_diligencia_diligencia
 FOREIGN KEY (id_diligencia)
 REFERENCES diligencias.diligencia (id_diligencia);

ALTER TABLE encargos.encargo_persona_diligencia
 ADD CONSTRAINT fk_encargo_persona_diligencia_persona
 FOREIGN KEY (id_persona_buscada)
 REFERENCES personas.persona (id_persona);

ALTER TABLE encargos.tarea_encargo
 ADD CONSTRAINT fk_tarea_encargo_tarea
 FOREIGN KEY (id_tarea)
 REFERENCES tareas.tarea (id_tarea);


-- =============================================================================
-- PASO 6 â€” DESCRIPCIONES
-- =============================================================================
-- Cada bloque es idempotente: actualiza la descripciÃ³n si existe, la crea
-- si no existe.
-- =============================================================================

-- ----- Esquema -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=SCHEMA_ID(N'encargos') AND class=3)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'GestiÃ³n de encargos: personas buscadas, Ã³rdenes judiciales del PJUD, presuntas desgracias. Cruza con denuncias, diligencias y tareas. Soporta los macroprocesos PO01 (InvestigaciÃ³n Criminal) y PO03 (CooperaciÃ³n Internacional).',
 @level0type=N'SCHEMA', @level0name=N'encargos';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'GestiÃ³n de encargos: personas buscadas, Ã³rdenes judiciales del PJUD, presuntas desgracias. Cruza con denuncias, diligencias y tareas. Soporta los macroprocesos PO01 (InvestigaciÃ³n Criminal) y PO03 (CooperaciÃ³n Internacional).',
 @level0type=N'SCHEMA', @level0name=N'encargos';


-- ----- Tabla: tipo_encargo -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('encargos.tipo_encargo') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'CatÃ¡logo de tipos de encargo: personas, armas, vehÃ­culos, otros.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'tipo_encargo';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'CatÃ¡logo de tipos de encargo: personas, armas, vehÃ­culos, otros.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'tipo_encargo';


-- ----- Tabla: tipo_orden_judicial -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('encargos.tipo_orden_judicial') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'CatÃ¡logo de tipos de orden judicial provenientes del PJUD.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'tipo_orden_judicial';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'CatÃ¡logo de tipos de orden judicial provenientes del PJUD.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'tipo_orden_judicial';


-- ----- Tabla: encargo -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('encargos.encargo') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Cabecera de todos los encargos del sistema con su vigencia.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'encargo';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Cabecera de todos los encargos del sistema con su vigencia.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'encargo';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('encargos.encargo')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('encargos.encargo'),N'fecha_inicio',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Inicio de vigencia del encargo (UTC).',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'encargo',
 @level2type=N'COLUMN', @level2name=N'fecha_inicio';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Inicio de vigencia del encargo (UTC).',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'encargo',
 @level2type=N'COLUMN', @level2name=N'fecha_inicio';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('encargos.encargo')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('encargos.encargo'),N'fecha_fin',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Fin de vigencia del encargo (UTC). NULL si estÃ¡ vigente.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'encargo',
 @level2type=N'COLUMN', @level2name=N'fecha_fin';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Fin de vigencia del encargo (UTC). NULL si estÃ¡ vigente.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'encargo',
 @level2type=N'COLUMN', @level2name=N'fecha_fin';


-- ----- Tabla: orden_judicial -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('encargos.orden_judicial') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Ã“rdenes judiciales provenientes del PJUD. id_orden_judicial es local (autogenerado en SIP), no se respeta el id externo del PJUD.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'orden_judicial';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Ã“rdenes judiciales provenientes del PJUD. id_orden_judicial es local (autogenerado en SIP), no se respeta el id externo del PJUD.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'orden_judicial';

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('encargos.orden_judicial')
 AND minor_id=COLUMNPROPERTY(OBJECT_ID('encargos.orden_judicial'),N'descripcion',N'COLUMN'))
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Facultades, modalidad horaria y condiciones de la orden judicial.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'orden_judicial',
 @level2type=N'COLUMN', @level2name=N'descripcion';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Facultades, modalidad horaria y condiciones de la orden judicial.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'orden_judicial',
 @level2type=N'COLUMN', @level2name=N'descripcion';


-- ----- Tabla: encargo_denuncia -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('encargos.encargo_denuncia') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Asocia denuncia de presunta desgracia con su encargo (relaciÃ³n 1:1).',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'encargo_denuncia';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Asocia denuncia de presunta desgracia con su encargo (relaciÃ³n 1:1).',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'encargo_denuncia';


-- ----- Tabla: encargo_orden_judicial -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('encargos.encargo_orden_judicial') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'RelaciÃ³n N:M entre encargos y Ã³rdenes judiciales.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'encargo_orden_judicial';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'RelaciÃ³n N:M entre encargos y Ã³rdenes judiciales.',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'encargo_orden_judicial';


-- ----- Tabla: encargo_persona_diligencia -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('encargos.encargo_persona_diligencia') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Asocia diligencia con encargo (relaciÃ³n 1:1, diligencia opcional).',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'encargo_persona_diligencia';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Asocia diligencia con encargo (relaciÃ³n 1:1, diligencia opcional).',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'encargo_persona_diligencia';


-- ----- Tabla: tarea_encargo -----

IF EXISTS (SELECT 1 FROM sys.extended_properties
 WHERE name=N'MS_Description' AND major_id=OBJECT_ID('encargos.tarea_encargo') AND minor_id=0 AND class=1)
 EXEC sys.sp_updateextendedproperty @name=N'MS_Description',
 @value=N'Tareas que crean o gestionan encargos (relaciÃ³n 1:1: una tarea = un encargo).',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'tarea_encargo';
ELSE
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Tareas que crean o gestionan encargos (relaciÃ³n 1:1: una tarea = un encargo).',
 @level0type=N'SCHEMA', @level0name=N'encargos', @level1type=N'TABLE', @level1name=N'tarea_encargo';


-- =============================================================================
-- FIN â€” V0003__nuevo_esquema_encargos
-- =============================================================================
-- ValidaciÃ³n recomendada (despuÃ©s de ejecutar):
-- SELECT COUNT(*) FROM sys.tables
-- WHERE schema_id = SCHEMA_ID('encargos'); -- esperado: 8
-- SELECT COUNT(*) FROM sys.foreign_keys fk
-- JOIN sys.tables t ON fk.parent_object_id = t.object_id
-- WHERE t.schema_id = SCHEMA_ID('encargos'); -- esperado: 13
-- SELECT COUNT(*) FROM sys.indexes i
-- JOIN sys.tables t ON i.object_id = t.object_id
-- WHERE t.schema_id = SCHEMA_ID('encargos')
-- AND i.is_primary_key = 0 AND i.is_unique_constraint = 0
-- AND i.type_desc = 'NONCLUSTERED'; -- esperado: 9
-- =============================================================================

