CREATE TABLE denuncias.denuncia_estado
(
id_denuncia_estado INT generated by default as identity PRIMARY KEY,
id_denuncia INT NOT NULL,
id_estado_denuncia INT NOT NULL,
id_funcionario INT NOT NULL,
fecha DATETIME2 NOT NULL
)

ALTER TABLE denuncias.denuncia_estado
ADD FOREIGN KEY (id_denuncia) REFERENCES denuncias.denuncia(id_denuncia)

ALTER TABLE denuncias.denuncia_estado
ADD FOREIGN KEY (id_estado_denuncia) REFERENCES denuncias.cat_estado_denuncia(id_estado_denuncia)

ALTER TABLE denuncias.denuncia_estado
ADD FOREIGN KEY (id_funcionario) REFERENCES organizacion.funcionario(id_funcionario)

