/* =============================================================================
 V0039 â€” ActualizaciÃ³n de archivos: catÃ¡logo de entidades vinculables y
 normalizaciÃ³n del discriminador de archivo_vinculo (ESTRUCTURA)
 PDI Chile â€” SIP. SQL Server. Flyway.

 Contexto
 El vÃ­nculo polimÃ³rfico usaba un discriminador de texto libre
 (esquema varchar(10) + entidad varchar(50)) sin integridad y con ancho
 insuficiente (esquema no admite nombres > 10, p. ej. 'diligencias').

 Cambios (solo estructura)
 - Crea archivos.cat_entidad_vinculable: catÃ¡logo de entidades vinculables
 (directorio esquema/entidad/PK). No lleva FK a los dominios (polimÃ³rfico).
 - Renombra la PK id_vinculo -> id_archivo_vinculo (convenciÃ³n PK = tabla).
 - Reemplaza (esquema, entidad) por id_entidad_vinculable (INT, FK al catÃ¡logo).
 - Reconstruye el UNIQUE y agrega Ã­ndice de lookup compacto.

 El SEED del catÃ¡logo vive en el repetible R__archivos_seeds.sql (corre despuÃ©s
 de las versionadas). La programabilidad (SP validador, detector) en
 R__archivos_programmability.sql.

 Nota: esta migraciÃ³n asume archivo_vinculo sin datos por resolver. Si hubiera
 filas, el paso 4 aborta con THROW (el poblado dependerÃ­a del seed, que es
 posterior; en ese caso los vÃ­nculos deben resolverse manualmente antes).

 Idempotente. TransacciÃ³n por migraciÃ³n de Flyway. XACT_ABORT ON.
 ============================================================================= */

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
SET NOCOUNT ON;

/* -----------------------------------------------------------------------------
 1) CatÃ¡logo cat_entidad_vinculable (generated by default as identity, patrÃ³n catÃ¡logo: 5 col. auditorÃ­a)
 ----------------------------------------------------------------------------- */
IF OBJECT_ID(N'archivos.cat_entidad_vinculable', N'U') IS NULL
BEGIN
 CREATE TABLE archivos.cat_entidad_vinculable (
 id_entidad_vinculable INTEGER generated by default as generated by default as identity NOT NULL,
 esquema SYSNAME NOT NULL,
 entidad SYSNAME NOT NULL,
 columna_pk SYSNAME NOT NULL,
 activo boolean NOT NULL CONSTRAINT df_cat_entidad_vinculable_activo DEFAULT (1),
 id_usuario_modificador INTEGER NULL,
 id_usuario_eliminador INTEGER NULL,
 fecha_creacion timestamp NULL,
 fecha_actualizacion timestamp NULL,
 fecha_eliminacion_logica timestamp NULL,
 CONSTRAINT pk_cat_entidad_vinculable PRIMARY KEY (id_entidad_vinculable),
 CONSTRAINT uq_cat_entidad_vinculable UNIQUE (esquema, entidad)
 );
END

/* -----------------------------------------------------------------------------
 2) Renombrar la PK: id_vinculo -> id_archivo_vinculo (convenciÃ³n PK = tabla).
 sp_rename conserva generated by default as identity y la PK; no recrea la tabla.
 ----------------------------------------------------------------------------- */
IF COL_LENGTH(N'archivos.archivo_vinculo', N'id_vinculo') IS NOT NULL
AND COL_LENGTH(N'archivos.archivo_vinculo', N'id_archivo_vinculo') IS NULL
BEGIN
 EXEC sp_rename N'archivos.archivo_vinculo.id_vinculo', N'id_archivo_vinculo', N'COLUMN';
END

/* -----------------------------------------------------------------------------
 3) Nueva columna id_entidad_vinculable (nullable de momento)
 ----------------------------------------------------------------------------- */
IF COL_LENGTH(N'archivos.archivo_vinculo', N'id_entidad_vinculable') IS NULL
 ALTER TABLE archivos.archivo_vinculo ADD id_entidad_vinculable INTEGER NULL;

/* -----------------------------------------------------------------------------
 4) Seguridad: esta migraciÃ³n estructural asume la tabla sin datos por resolver.
 Si existieran vÃ­nculos (con columnas de texto aÃºn presentes), abortar: deben
 resolverse manualmente porque el seed del catÃ¡logo es posterior (repetible).
 ----------------------------------------------------------------------------- */
IF COL_LENGTH(N'archivos.archivo_vinculo', N'entidad') IS NOT NULL
 AND EXISTS (SELECT 1 FROM archivos.archivo_vinculo)
BEGIN
 THROW 50039, N'V0039: archivo_vinculo tiene datos. Resolver id_entidad_vinculable antes de aplicar (el seed del catÃ¡logo corre como repetible, posterior a esta migraciÃ³n).', 1;
END

/* -----------------------------------------------------------------------------
 5) id_entidad_vinculable NOT NULL (tabla vacÃ­a -> sin default necesario)
 ----------------------------------------------------------------------------- */
IF EXISTS (
 SELECT 1 FROM sys.columns
 WHERE object_id = OBJECT_ID(N'archivos.archivo_vinculo')
 AND name = N'id_entidad_vinculable' AND is_nullable = 1
)
 ALTER TABLE archivos.archivo_vinculo ALTER COLUMN id_entidad_vinculable INTEGER NOT NULL;

/* -----------------------------------------------------------------------------
 6) Constraints: soltar UNIQUE viejo (usa esquema/entidad), FK al catÃ¡logo,
 UNIQUE nuevo
 ----------------------------------------------------------------------------- */
IF EXISTS (SELECT 1 FROM sys.objects WHERE name = N'uq_vinculo_archivo_entidad' AND parent_object_id = OBJECT_ID(N'archivos.archivo_vinculo'))
 ALTER TABLE archivos.archivo_vinculo DROP CONSTRAINT uq_vinculo_archivo_entidad;

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name = N'fk_vinculo_entidad' AND type = N'F')
 ALTER TABLE archivos.archivo_vinculo
 ADD CONSTRAINT fk_vinculo_entidad FOREIGN KEY (id_entidad_vinculable)
 REFERENCES archivos.cat_entidad_vinculable (id_entidad_vinculable);

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name = N'uq_vinculo_archivo_entidad' AND parent_object_id = OBJECT_ID(N'archivos.archivo_vinculo'))
 ALTER TABLE archivos.archivo_vinculo
 ADD CONSTRAINT uq_vinculo_archivo_entidad UNIQUE (id_archivo, id_entidad_vinculable, id_entidad);

/* -----------------------------------------------------------------------------
 7) Eliminar el discriminador de texto (esquema, entidad)
 ----------------------------------------------------------------------------- */
IF COL_LENGTH(N'archivos.archivo_vinculo', N'entidad') IS NOT NULL
 ALTER TABLE archivos.archivo_vinculo DROP COLUMN entidad;
IF COL_LENGTH(N'archivos.archivo_vinculo', N'esquema') IS NOT NULL
 ALTER TABLE archivos.archivo_vinculo DROP COLUMN esquema;

/* -----------------------------------------------------------------------------
 8) Ãndice de lookup compacto
 ----------------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_vinculo_entidad' AND object_id = OBJECT_ID(N'archivos.archivo_vinculo'))
 CREATE NONCLUSTERED INDEX ix_vinculo_entidad
 ON archivos.archivo_vinculo (id_entidad_vinculable, id_entidad)
 INCLUDE (id_archivo)
 WHERE fecha_eliminacion_logica IS NULL;

/* -----------------------------------------------------------------------------
 9) Descripciones (MS_Description)
 ----------------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'archivos.cat_entidad_vinculable') AND minor_id = 0 AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty
 @name=N'MS_Description',
 @value=N'CatÃ¡logo de entidades que pueden vincularse a un archivo. Define cada entidad vinculable (esquema, entidad, columna PK) para resolver el vÃ­nculo polimÃ³rfico. No tiene FK a los dominios.',
 @level0type=N'SCHEMA', @level0name=N'archivos',
 @level1type=N'TABLE', @level1name=N'cat_entidad_vinculable';

IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'archivos.archivo_vinculo') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'archivos.archivo_vinculo'), N'id_entidad_vinculable', N'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty
 @name=N'MS_Description',
 @value=N'Entidad vinculable a la que se asocia el archivo (quÃ© tabla). FK a archivos.cat_entidad_vinculable. Junto con id_entidad (quÃ© fila) resuelve la referencia polimÃ³rfica.',
 @level0type=N'SCHEMA', @level0name=N'archivos',
 @level1type=N'TABLE', @level1name=N'archivo_vinculo',
 @level2type=N'COLUMN', @level2name=N'id_entidad_vinculable';

