CREATE TABLE ubicacion.cat_tipo_poblacion
(
id_tipo_poblacion INT generated by default as generated by default as identity NOT NULL PRIMARY KEY,
descripcion varchar(50) NOT NULL,
id_usuario_modificador INT NULL,
id_usuario_eliminador INT NULL,
fecha_creacion timestamp NULL,
fecha_actualizacion timestamp NULL,
fecha_eliminacion_logica timestamp NULL
)

ALTER TABLE ubicacion.lugar_base
ADD id_tipo_poblacion INT NULL

ALTER TABLE ubicacion.lugar_base
ADD FOREIGN KEY (id_tipo_poblacion) REFERENCES ubicacion.cat_tipo_poblacion(id_tipo_poblacion)

