-- =============================================================================
-- SIP â€” Migration V0045__pauta_nna
-- =============================================================================
-- Compatible: SQL Server 2017+ (forward-compatible 2022)
-- Depende de: V0001__baseline_sip.sql (denuncias.denuncia, casos.caso,
-- personas.persona, organizacion.funcionario)
--
-- ALCANCE (PDI-1553 â€” Registro adulto responsable / ANEXO NÂ°3 "Formulario de
-- Factores de Riesgo NNA", Ley 21.057):
-- 1. Crea catÃ¡logos nuevos en el esquema denuncias:
-- - denuncias.cat_tipo_acompanamiento_nna (cÃ³mo se presenta el NNA)
-- - denuncias.cat_tipo_denunciante_nna (quiÃ©n denuncia: adulto o NNA)
-- - denuncias.cat_categoria_factor_riesgo_nna (5 secciones del Anexo NÂ°3)
-- - denuncias.cat_factor_riesgo_nna (25 Ã­tems del checklist)
-- 2. Agrega personas.persona.edad_declarada (SMALLINT NULL): edad aproximada
-- auto-reportada, usada cuando no se dispone de fecha_nacimiento exacta
-- (vÃ­ctima NNA, acompaÃ±ante, adulto protector o agresor capturados en
-- este formulario).
-- 3. Crea denuncias.pauta_nna: cabecera 1:1 (opcional) con denuncia o caso,
-- con los campos propios del Anexo NÂ°3 que no son responsabilidad de otro
-- esquema (NÂ° de parte/denuncia, fecha del formulario, delito aparente).
-- La identificaciÃ³n de vÃ­ctima/acompaÃ±ante/adulto protector/agresor NO se
-- duplica aquÃ­: se modela como personas.persona vinculadas a la denuncia
-- vÃ­a denuncias.denuncia_persona_rol (roles nuevos, ver BLOQUE 4) y sus
-- relaciones vÃ­a personas.relacion + personas.cat_tipo_relacion
-- (catÃ¡logo ya existente, reutilizado).
-- 4. Crea denuncias.pauta_nna_factor_riesgo: respuesta (SI/NO/NO_SABE) +
-- observaciÃ³n por cada Ã­tem del checklist, para la pauta.
-- 5. Agrega cÃ³digos nuevos a casos.cat_tipo_rol_persona:
-- - ACOMPANANTE_NNA (acompaÃ±ante del NNA)
-- - ADULTO_PROTECTOR_NNA (adulto protector, solo si es distinto al
-- acompaÃ±ante â€” el Anexo NÂ°3 los trata como
-- identificaciones separadas)
-- - AGRESOR_NNA (agresor identificado espontÃ¡neamente, no
-- formalizado como IMPUTADO)
-- El seed real (MERGE) se aplica en R__casos_seeds.sql.
--
-- DATOS PRODUCTIVOS:
-- Esta migration no mueve datos existentes; solo agrega estructura nueva.
--
-- IDEMPOTENCIA:
-- Guardas IF OBJECT_ID / IF COL_LENGTH IS NULL en todos los bloques.
-- =============================================================================
SET ANSI_NULLS ON;
SET ANSI_WARNINGS ON;
SET ANSI_PADDING ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;


-- =============================================================================
-- BLOQUE 1 â€” CATÃLOGOS NUEVOS
-- =============================================================================
-- Mismo patrÃ³n que denuncias.cat_estado_denuncia (V0007): id generated by default as identity,
-- codigo Ãºnico, nombre descriptivo, orden para presentaciÃ³n, es_activo para
-- baja lÃ³gica.
-- =============================================================================

-- â”€â”€â”€ denuncias.cat_tipo_acompanamiento_nna â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF OBJECT_ID('denuncias.cat_tipo_acompanamiento_nna', 'U') IS NULL
BEGIN
 CREATE TABLE denuncias.cat_tipo_acompanamiento_nna (
 id_tipo_acompanamiento_nna INTEGER NOT NULL generated by default as generated by default as identity,
 codigo varchar(30) NOT NULL,
 nombre varchar(80) NOT NULL,
 orden INTEGER NULL,
 es_activo boolean NOT NULL CONSTRAINT df_cat_tipo_acompanamiento_nna_es_activo DEFAULT (1),
 CONSTRAINT pk_cat_tipo_acompanamiento_nna
 PRIMARY KEY (id_tipo_acompanamiento_nna),
 CONSTRAINT uq_cat_tipo_acompanamiento_nna_codigo
 UNIQUE (codigo)
 );
END;

-- â”€â”€â”€ denuncias.cat_tipo_denunciante_nna â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF OBJECT_ID('denuncias.cat_tipo_denunciante_nna', 'U') IS NULL
BEGIN
 CREATE TABLE denuncias.cat_tipo_denunciante_nna (
 id_tipo_denunciante_nna INTEGER NOT NULL generated by default as generated by default as identity,
 codigo varchar(30) NOT NULL,
 nombre varchar(80) NOT NULL,
 orden INTEGER NULL,
 es_activo boolean NOT NULL CONSTRAINT df_cat_tipo_denunciante_nna_es_activo DEFAULT (1),
 CONSTRAINT pk_cat_tipo_denunciante_nna
 PRIMARY KEY (id_tipo_denunciante_nna),
 CONSTRAINT uq_cat_tipo_denunciante_nna_codigo
 UNIQUE (codigo)
 );
END;


-- =============================================================================
-- BLOQUE 2 â€” personas.persona.edad_declarada
-- =============================================================================
-- Edad aproximada auto-reportada por la propia persona (o por quien la
-- acompaÃ±a), para los casos en que no se dispone de fecha_nacimiento exacta.
-- No reemplaza fecha_nacimiento; conviven ambas columnas.
-- =============================================================================
IF COL_LENGTH(N'personas.persona', N'edad_declarada') IS NULL
 ALTER TABLE personas.persona ADD edad_declarada SMALLINT NULL;


-- =============================================================================
-- BLOQUE 3 â€” denuncias.pauta_nna (cabecera)
-- =============================================================================
-- Sigue el patrÃ³n estructural de denuncias.pauta_vif (V0001): FK opcional a
-- denuncia y a caso, id_funcionario_registra obligatorio, columnas de
-- auditorÃ­a incorporadas desde el origen (no requieren el ALTER posterior
-- que sÃ­ necesitÃ³ pauta_vif en V0027).
-- =============================================================================
IF OBJECT_ID('denuncias.pauta_nna', 'U') IS NULL
BEGIN
 CREATE TABLE denuncias.pauta_nna (
 id_pauta_nna INTEGER NOT NULL generated by default as generated by default as identity,
 id_denuncia INTEGER NULL,
 id_caso INTEGER NULL,
 numero_parte_denuncia varchar(50) NULL,
 fecha_formulario DATE NULL,
 id_tipo_acompanamiento_nna INTEGER NOT NULL,
 id_tipo_denunciante_nna INTEGER NOT NULL,
 delito_aparente varchar(200) NULL,
 observaciones varchar(2000) NULL,
 id_funcionario_registra INTEGER NOT NULL,
 fecha_creacion timestamp NOT NULL CONSTRAINT df_pauta_nna_fecha_creacion DEFAULT CURRENT_TIMESTAMP,
 fecha_actualizacion timestamp NULL,
 id_usuario_creador INT NOT NULL,
 id_usuario_modificador INT NULL,
 id_usuario_eliminador INT NULL,
 fecha_eliminacion_logica timestamp NULL,
 CONSTRAINT pk_pauta_nna
 PRIMARY KEY (id_pauta_nna),
 CONSTRAINT fk_pauta_nna_denuncia
 FOREIGN KEY (id_denuncia) REFERENCES denuncias.denuncia (id_denuncia),
 CONSTRAINT fk_pauta_nna_caso
 FOREIGN KEY (id_caso) REFERENCES casos.caso (id_caso),
 CONSTRAINT fk_pauta_nna_tipo_acompanamiento
 FOREIGN KEY (id_tipo_acompanamiento_nna) REFERENCES denuncias.cat_tipo_acompanamiento_nna (id_tipo_acompanamiento_nna),
 CONSTRAINT fk_pauta_nna_tipo_denunciante
 FOREIGN KEY (id_tipo_denunciante_nna) REFERENCES denuncias.cat_tipo_denunciante_nna (id_tipo_denunciante_nna),
 CONSTRAINT fk_pauta_nna_funcionario_registra
 FOREIGN KEY (id_funcionario_registra) REFERENCES organizacion.funcionario (id_funcionario),
 CONSTRAINT fk_pauta_nna_usuario_creador
 FOREIGN KEY (id_usuario_creador) REFERENCES auth.usuario (id_usuario),
 CONSTRAINT fk_pauta_nna_usuario_modificador
 FOREIGN KEY (id_usuario_modificador) REFERENCES auth.usuario (id_usuario),
 CONSTRAINT fk_pauta_nna_usuario_eliminador
 FOREIGN KEY (id_usuario_eliminador) REFERENCES auth.usuario (id_usuario)
 );
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_pauta_nna_denuncia' AND object_id = OBJECT_ID(N'denuncias.pauta_nna'))
 CREATE INDEX ix_pauta_nna_denuncia ON denuncias.pauta_nna (id_denuncia) WHERE id_denuncia IS NOT NULL;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_pauta_nna_caso' AND object_id = OBJECT_ID(N'denuncias.pauta_nna'))
 CREATE INDEX ix_pauta_nna_caso ON denuncias.pauta_nna (id_caso) WHERE id_caso IS NOT NULL;


-- =============================================================================
-- BLOQUE 4 â€” denuncias.cat_categoria_factor_riesgo_nna
-- =============================================================================
-- Las 5 secciones del checklist del Anexo NÂ°3 (Gravedad del delito, Factores
-- asociados a la vÃ­ctima, Contacto del Agresor con la vÃ­ctima, Antecedentes
-- del Agresor, Conducta del adulto protector/responsable/referente).
-- =============================================================================
IF OBJECT_ID('denuncias.cat_categoria_factor_riesgo_nna', 'U') IS NULL
BEGIN
 CREATE TABLE denuncias.cat_categoria_factor_riesgo_nna (
 id_categoria_factor_riesgo_nna INTEGER NOT NULL generated by default as generated by default as identity,
 codigo varchar(40) NOT NULL,
 nombre varchar(150) NOT NULL,
 orden INTEGER NULL,
 es_activo boolean NOT NULL CONSTRAINT df_cat_categoria_factor_riesgo_nna_es_activo DEFAULT (1),
 CONSTRAINT pk_cat_categoria_factor_riesgo_nna
 PRIMARY KEY (id_categoria_factor_riesgo_nna),
 CONSTRAINT uq_cat_categoria_factor_riesgo_nna_codigo
 UNIQUE (codigo)
 );
END;


-- =============================================================================
-- BLOQUE 5 â€” denuncias.cat_factor_riesgo_nna
-- =============================================================================
-- Los 25 Ã­tems del checklist, cada uno asociado a una categorÃ­a. El seed
-- (25 filas, texto exacto del Anexo NÂ°3) se aplica vÃ­a MERGE idempotente en
-- migrations/repeatable/R__denuncias_seeds.sql.
-- =============================================================================
IF OBJECT_ID('denuncias.cat_factor_riesgo_nna', 'U') IS NULL
BEGIN
 CREATE TABLE denuncias.cat_factor_riesgo_nna (
 id_factor_riesgo_nna INTEGER NOT NULL generated by default as generated by default as identity,
 id_categoria_factor_riesgo_nna INTEGER NOT NULL,
 codigo varchar(60) NOT NULL,
 nombre varchar(150) NOT NULL,
 descripcion varchar(400) NOT NULL,
 orden INTEGER NULL,
 es_activo boolean NOT NULL CONSTRAINT df_cat_factor_riesgo_nna_es_activo DEFAULT (1),
 CONSTRAINT pk_cat_factor_riesgo_nna
 PRIMARY KEY (id_factor_riesgo_nna),
 CONSTRAINT uq_cat_factor_riesgo_nna_codigo
 UNIQUE (codigo),
 CONSTRAINT fk_cat_factor_riesgo_nna_categoria
 FOREIGN KEY (id_categoria_factor_riesgo_nna) REFERENCES denuncias.cat_categoria_factor_riesgo_nna (id_categoria_factor_riesgo_nna)
 );
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_cat_factor_riesgo_nna_categoria' AND object_id = OBJECT_ID(N'denuncias.cat_factor_riesgo_nna'))
 CREATE INDEX ix_cat_factor_riesgo_nna_categoria ON denuncias.cat_factor_riesgo_nna (id_categoria_factor_riesgo_nna);


-- =============================================================================
-- BLOQUE 6 â€” denuncias.pauta_nna_factor_riesgo (respuestas del checklist)
-- =============================================================================
-- Una fila por (pauta_nna, factor_riesgo_nna) respondida. respuesta usa CHECK
-- de dominio cerrado (SI/NO/NO_SABE) en vez de catÃ¡logo aparte: es un valor
-- fijo de 3 estados que no requiere administraciÃ³n ni crecerÃ¡.
-- =============================================================================
IF OBJECT_ID('denuncias.pauta_nna_factor_riesgo', 'U') IS NULL
BEGIN
 CREATE TABLE denuncias.pauta_nna_factor_riesgo (
 id_pauta_nna_factor_riesgo INTEGER NOT NULL generated by default as generated by default as identity,
 id_pauta_nna INTEGER NOT NULL,
 id_factor_riesgo_nna INTEGER NOT NULL,
 respuesta varchar(10) NULL,
 observaciones varchar(500) NULL,
 fecha_creacion timestamp NOT NULL CONSTRAINT df_pauta_nna_factor_riesgo_fecha_creacion DEFAULT CURRENT_TIMESTAMP,
 fecha_actualizacion timestamp NULL,
 CONSTRAINT pk_pauta_nna_factor_riesgo
 PRIMARY KEY (id_pauta_nna_factor_riesgo),
 CONSTRAINT fk_pauta_nna_factor_riesgo_pauta
 FOREIGN KEY (id_pauta_nna) REFERENCES denuncias.pauta_nna (id_pauta_nna),
 CONSTRAINT fk_pauta_nna_factor_riesgo_factor
 FOREIGN KEY (id_factor_riesgo_nna) REFERENCES denuncias.cat_factor_riesgo_nna (id_factor_riesgo_nna),
 CONSTRAINT uq_pauta_nna_factor_riesgo
 UNIQUE (id_pauta_nna, id_factor_riesgo_nna),
 CONSTRAINT ck_pauta_nna_factor_riesgo_respuesta
 CHECK (respuesta IN ('SI','NO','NO_SABE'))
 );
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_pauta_nna_factor_riesgo_pauta' AND object_id = OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo'))
 CREATE INDEX ix_pauta_nna_factor_riesgo_pauta ON denuncias.pauta_nna_factor_riesgo (id_pauta_nna);


-- =============================================================================
-- BLOQUE 7 â€” Nuevos roles en casos.cat_tipo_rol_persona (estructura)
-- =============================================================================
-- Solo se valida aquÃ­ que la tabla exista (creada en V0001). El seed de las
-- filas ACOMPANANTE_NNA / ADULTO_PROTECTOR_NNA / AGRESOR_NNA se aplica vÃ­a
-- MERGE idempotente en migrations/repeatable/R__casos_seeds.sql (mismo
-- mecanismo usado para VICTIMA_NNA), para mantener un Ãºnico punto de verdad
-- de los datos del catÃ¡logo.
-- =============================================================================


-- =============================================================================
-- BLOQUE 8 â€” DESCRIPCIONES EXTENDIDAS (MS_Description)
-- =============================================================================

-- â”€â”€â”€ denuncias.cat_tipo_acompanamiento_nna â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_tipo_acompanamiento_nna') AND minor_id = 0 AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'CatÃ¡logo de formas en que se presenta el NNA a denunciar (ej: acompaÃ±ado por adulto, solo, derivado). Item del Anexo NÂ°3 "Formulario de Factores de Riesgo NNA" (Ley 21.057).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_acompanamiento_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_tipo_acompanamiento_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_tipo_acompanamiento_nna'), N'id_tipo_acompanamiento_nna', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del tipo de acompaÃ±amiento. Clave primaria autogenerada por el motor.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_acompanamiento_nna',@level2type=N'COLUMN',@level2name=N'id_tipo_acompanamiento_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_tipo_acompanamiento_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_tipo_acompanamiento_nna'), N'codigo', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'CÃ³digo abreviado del tipo de acompaÃ±amiento, en mayÃºsculas. Inmutable una vez creado el catÃ¡logo.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_acompanamiento_nna',@level2type=N'COLUMN',@level2name=N'codigo';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_tipo_acompanamiento_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_tipo_acompanamiento_nna'), N'nombre', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Nombre descriptivo del tipo de acompaÃ±amiento para presentaciÃ³n en interfaces y reportes.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_acompanamiento_nna',@level2type=N'COLUMN',@level2name=N'nombre';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_tipo_acompanamiento_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_tipo_acompanamiento_nna'), N'orden', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Orden numÃ©rico de presentaciÃ³n del Ã­tem en interfaces y reportes.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_acompanamiento_nna',@level2type=N'COLUMN',@level2name=N'orden';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_tipo_acompanamiento_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_tipo_acompanamiento_nna'), N'es_activo', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Indicador lÃ³gico de actividad del Ã­tem. 1 = activo (admitido para nuevas pautas), 0 = inactivo (preserva trazabilidad histÃ³rica).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_acompanamiento_nna',@level2type=N'COLUMN',@level2name=N'es_activo';

IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_tipo_acompanamiento_nna', N'CONSTRAINT', N'pk_cat_tipo_acompanamiento_nna'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Clave primaria autonumÃ©rica del catÃ¡logo.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_acompanamiento_nna',@level2type=N'CONSTRAINT',@level2name=N'pk_cat_tipo_acompanamiento_nna';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_tipo_acompanamiento_nna', N'CONSTRAINT', N'uq_cat_tipo_acompanamiento_nna_codigo'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Garantiza que el cÃ³digo del tipo de acompaÃ±amiento sea Ãºnico en el catÃ¡logo.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_acompanamiento_nna',@level2type=N'CONSTRAINT',@level2name=N'uq_cat_tipo_acompanamiento_nna_codigo';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_tipo_acompanamiento_nna', N'CONSTRAINT', N'df_cat_tipo_acompanamiento_nna_es_activo'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Valor por defecto de es_activo: todo Ã­tem nuevo nace activo (1).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_acompanamiento_nna',@level2type=N'CONSTRAINT',@level2name=N'df_cat_tipo_acompanamiento_nna_es_activo';

-- â”€â”€â”€ denuncias.cat_tipo_denunciante_nna â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_tipo_denunciante_nna') AND minor_id = 0 AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'CatÃ¡logo de tipos de denunciante del Anexo NÂ°3 (quiÃ©n denuncia: el propio NNA o un adulto en su representaciÃ³n).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_denunciante_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_tipo_denunciante_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_tipo_denunciante_nna'), N'id_tipo_denunciante_nna', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del tipo de denunciante. Clave primaria autogenerada por el motor.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_denunciante_nna',@level2type=N'COLUMN',@level2name=N'id_tipo_denunciante_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_tipo_denunciante_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_tipo_denunciante_nna'), N'codigo', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'CÃ³digo abreviado del tipo de denunciante, en mayÃºsculas. Inmutable una vez creado el catÃ¡logo.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_denunciante_nna',@level2type=N'COLUMN',@level2name=N'codigo';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_tipo_denunciante_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_tipo_denunciante_nna'), N'nombre', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Nombre descriptivo del tipo de denunciante para presentaciÃ³n en interfaces y reportes.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_denunciante_nna',@level2type=N'COLUMN',@level2name=N'nombre';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_tipo_denunciante_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_tipo_denunciante_nna'), N'orden', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Orden numÃ©rico de presentaciÃ³n del Ã­tem en interfaces y reportes.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_denunciante_nna',@level2type=N'COLUMN',@level2name=N'orden';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_tipo_denunciante_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_tipo_denunciante_nna'), N'es_activo', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Indicador lÃ³gico de actividad del Ã­tem. 1 = activo (admitido para nuevas pautas), 0 = inactivo (preserva trazabilidad histÃ³rica).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_denunciante_nna',@level2type=N'COLUMN',@level2name=N'es_activo';

IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_tipo_denunciante_nna', N'CONSTRAINT', N'pk_cat_tipo_denunciante_nna'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Clave primaria autonumÃ©rica del catÃ¡logo.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_denunciante_nna',@level2type=N'CONSTRAINT',@level2name=N'pk_cat_tipo_denunciante_nna';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_tipo_denunciante_nna', N'CONSTRAINT', N'uq_cat_tipo_denunciante_nna_codigo'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Garantiza que el cÃ³digo del tipo de denunciante sea Ãºnico en el catÃ¡logo.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_denunciante_nna',@level2type=N'CONSTRAINT',@level2name=N'uq_cat_tipo_denunciante_nna_codigo';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_tipo_denunciante_nna', N'CONSTRAINT', N'df_cat_tipo_denunciante_nna_es_activo'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Valor por defecto de es_activo: todo Ã­tem nuevo nace activo (1).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_tipo_denunciante_nna',@level2type=N'CONSTRAINT',@level2name=N'df_cat_tipo_denunciante_nna_es_activo';

-- â”€â”€â”€ personas.persona.edad_declarada â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'personas.persona') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'personas.persona'), N'edad_declarada', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Edad aproximada auto-reportada por la persona (o por quien la acompaÃ±a), usada cuando no se dispone de fecha_nacimiento exacta. No reemplaza fecha_nacimiento; ambas columnas conviven.',
 @level0type=N'SCHEMA',@level0name=N'personas',@level1type=N'TABLE',@level1name=N'persona',@level2type=N'COLUMN',@level2name=N'edad_declarada';

-- â”€â”€â”€ denuncias.pauta_nna â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = 0 AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Cabecera 1:1 (opcional) con denuncia o caso, con los campos propios del Anexo NÂ°3 "Formulario de Factores de Riesgo NNA" (Ley 21.057) que no son responsabilidad de otro esquema. La identificaciÃ³n de vÃ­ctima/acompaÃ±ante/adulto protector/agresor se modela vÃ­a denuncias.denuncia_persona_rol, no aquÃ­.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'id_pauta_nna', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico de la pauta NNA. Clave primaria autogenerada por el motor.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'id_pauta_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'id_denuncia', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK opcional a denuncias.denuncia. NULL si la pauta estÃ¡ asociada a un caso en vez de a una denuncia.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'id_denuncia';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'id_caso', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK opcional a casos.caso. NULL si la pauta estÃ¡ asociada a una denuncia en vez de a un caso.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'id_caso';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'numero_parte_denuncia', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'NÂ° de parte/denuncia policial asociado al formulario del Anexo NÂ°3.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'numero_parte_denuncia';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'fecha_formulario', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Fecha de aplicaciÃ³n del formulario del Anexo NÂ°3.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'fecha_formulario';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'id_tipo_acompanamiento_nna', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a denuncias.cat_tipo_acompanamiento_nna: cÃ³mo se presenta el NNA en la denuncia.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'id_tipo_acompanamiento_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'id_tipo_denunciante_nna', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a denuncias.cat_tipo_denunciante_nna: quiÃ©n denuncia (el NNA o un adulto en su representaciÃ³n).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'id_tipo_denunciante_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'delito_aparente', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'DescripciÃ³n del delito aparente informado en el formulario.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'delito_aparente';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'observaciones', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Observaciones libres registradas por el funcionario al aplicar el formulario.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'observaciones';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'id_funcionario_registra', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK obligatoria a organizacion.funcionario: quiÃ©n registrÃ³ la pauta.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'id_funcionario_registra';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'fecha_creacion', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Fecha/hora UTC de creaciÃ³n del registro. Asignada por el motor via CURRENT_TIMESTAMP.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'fecha_creacion';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'fecha_actualizacion', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Fecha/hora UTC de la Ãºltima actualizaciÃ³n del registro. NULL si nunca se ha modificado.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'fecha_actualizacion';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'id_usuario_creador', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK obligatoria a auth.usuario: quiÃ©n creÃ³ el registro.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'id_usuario_creador';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'id_usuario_modificador', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK opcional a auth.usuario: quiÃ©n realizÃ³ la Ãºltima modificaciÃ³n. NULL si nunca se ha modificado.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'id_usuario_modificador';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'id_usuario_eliminador', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK opcional a auth.usuario: quiÃ©n realizÃ³ la baja lÃ³gica. NULL si el registro no ha sido eliminado.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'id_usuario_eliminador';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna'), N'fecha_eliminacion_logica', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Fecha/hora UTC de baja lÃ³gica del registro. NULL si el registro estÃ¡ vigente.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'COLUMN',@level2name=N'fecha_eliminacion_logica';

IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna', N'CONSTRAINT', N'pk_pauta_nna'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Clave primaria autonumÃ©rica de la pauta NNA.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'CONSTRAINT',@level2name=N'pk_pauta_nna';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna', N'CONSTRAINT', N'fk_pauta_nna_tipo_acompanamiento'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a denuncias.cat_tipo_acompanamiento_nna: cÃ³mo se presenta el NNA en la denuncia.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'CONSTRAINT',@level2name=N'fk_pauta_nna_tipo_acompanamiento';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna', N'CONSTRAINT', N'fk_pauta_nna_tipo_denunciante'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a denuncias.cat_tipo_denunciante_nna: quiÃ©n denuncia (el NNA o un adulto en su representaciÃ³n).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'CONSTRAINT',@level2name=N'fk_pauta_nna_tipo_denunciante';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna', N'CONSTRAINT', N'fk_pauta_nna_funcionario_registra'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a organizacion.funcionario: quiÃ©n registrÃ³ la pauta.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'CONSTRAINT',@level2name=N'fk_pauta_nna_funcionario_registra';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna', N'CONSTRAINT', N'fk_pauta_nna_usuario_creador'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK del bloque de auditorÃ­a estÃ¡ndar SIP: referencia a auth.usuario (usuario creador).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'CONSTRAINT',@level2name=N'fk_pauta_nna_usuario_creador';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna', N'CONSTRAINT', N'fk_pauta_nna_usuario_modificador'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK del bloque de auditorÃ­a estÃ¡ndar SIP: referencia a auth.usuario (usuario modificador).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'CONSTRAINT',@level2name=N'fk_pauta_nna_usuario_modificador';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna', N'CONSTRAINT', N'fk_pauta_nna_usuario_eliminador'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK del bloque de auditorÃ­a estÃ¡ndar SIP: referencia a auth.usuario (usuario eliminador).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'CONSTRAINT',@level2name=N'fk_pauta_nna_usuario_eliminador';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna', N'CONSTRAINT', N'df_pauta_nna_fecha_creacion'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Valor por defecto de fecha_creacion: red de seguridad para asegurar UTC aunque el procedimiento no la puebla explÃ­citamente.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'CONSTRAINT',@level2name=N'df_pauta_nna_fecha_creacion';

-- â”€â”€â”€ denuncias.cat_categoria_factor_riesgo_nna â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_categoria_factor_riesgo_nna') AND minor_id = 0 AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'CatÃ¡logo de las 5 secciones del checklist del Anexo NÂ°3 (Gravedad del delito, Factores asociados a la vÃ­ctima, Contacto del Agresor con la vÃ­ctima, Antecedentes del Agresor, Conducta del adulto protector/responsable/referente).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_categoria_factor_riesgo_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_categoria_factor_riesgo_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_categoria_factor_riesgo_nna'), N'id_categoria_factor_riesgo_nna', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico de la categorÃ­a de factor de riesgo. Clave primaria autogenerada por el motor.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_categoria_factor_riesgo_nna',@level2type=N'COLUMN',@level2name=N'id_categoria_factor_riesgo_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_categoria_factor_riesgo_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_categoria_factor_riesgo_nna'), N'codigo', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'CÃ³digo abreviado de la categorÃ­a, en mayÃºsculas. Inmutable una vez creado el catÃ¡logo.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_categoria_factor_riesgo_nna',@level2type=N'COLUMN',@level2name=N'codigo';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_categoria_factor_riesgo_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_categoria_factor_riesgo_nna'), N'nombre', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Nombre descriptivo de la categorÃ­a para presentaciÃ³n en interfaces y reportes.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_categoria_factor_riesgo_nna',@level2type=N'COLUMN',@level2name=N'nombre';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_categoria_factor_riesgo_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_categoria_factor_riesgo_nna'), N'orden', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Orden numÃ©rico de presentaciÃ³n de la secciÃ³n en interfaces y reportes.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_categoria_factor_riesgo_nna',@level2type=N'COLUMN',@level2name=N'orden';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_categoria_factor_riesgo_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_categoria_factor_riesgo_nna'), N'es_activo', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Indicador lÃ³gico de actividad de la categorÃ­a. 1 = activo, 0 = inactivo (preserva trazabilidad histÃ³rica).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_categoria_factor_riesgo_nna',@level2type=N'COLUMN',@level2name=N'es_activo';

IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_categoria_factor_riesgo_nna', N'CONSTRAINT', N'pk_cat_categoria_factor_riesgo_nna'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Clave primaria autonumÃ©rica del catÃ¡logo.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_categoria_factor_riesgo_nna',@level2type=N'CONSTRAINT',@level2name=N'pk_cat_categoria_factor_riesgo_nna';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_categoria_factor_riesgo_nna', N'CONSTRAINT', N'uq_cat_categoria_factor_riesgo_nna_codigo'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Garantiza que el cÃ³digo de la categorÃ­a sea Ãºnico en el catÃ¡logo.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_categoria_factor_riesgo_nna',@level2type=N'CONSTRAINT',@level2name=N'uq_cat_categoria_factor_riesgo_nna_codigo';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_categoria_factor_riesgo_nna', N'CONSTRAINT', N'df_cat_categoria_factor_riesgo_nna_es_activo'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Valor por defecto de es_activo: toda categorÃ­a nueva nace activa (1).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_categoria_factor_riesgo_nna',@level2type=N'CONSTRAINT',@level2name=N'df_cat_categoria_factor_riesgo_nna_es_activo';

-- â”€â”€â”€ denuncias.cat_factor_riesgo_nna â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_factor_riesgo_nna') AND minor_id = 0 AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'CatÃ¡logo de los 25 Ã­tems del checklist del Anexo NÂ°3, cada uno asociado a una categorÃ­a (denuncias.cat_categoria_factor_riesgo_nna). Seed vÃ­a MERGE en R__denuncias_seeds.sql.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_factor_riesgo_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_factor_riesgo_nna'), N'id_factor_riesgo_nna', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico del Ã­tem del checklist. Clave primaria autogenerada por el motor.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna',@level2type=N'COLUMN',@level2name=N'id_factor_riesgo_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_factor_riesgo_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_factor_riesgo_nna'), N'id_categoria_factor_riesgo_nna', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a denuncias.cat_categoria_factor_riesgo_nna: secciÃ³n del Anexo NÂ°3 a la que pertenece el Ã­tem.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna',@level2type=N'COLUMN',@level2name=N'id_categoria_factor_riesgo_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_factor_riesgo_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_factor_riesgo_nna'), N'codigo', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'CÃ³digo abreviado del Ã­tem, en mayÃºsculas. Inmutable una vez creado el catÃ¡logo.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna',@level2type=N'COLUMN',@level2name=N'codigo';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_factor_riesgo_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_factor_riesgo_nna'), N'nombre', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Etiqueta corta y presentable del Ã­tem, derivada de descripcion, para uso en interfaces donde el texto completo del checklist es demasiado extenso.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna',@level2type=N'COLUMN',@level2name=N'nombre';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_factor_riesgo_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_factor_riesgo_nna'), N'descripcion', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Texto exacto del Ã­tem del checklist del Anexo NÂ°3.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna',@level2type=N'COLUMN',@level2name=N'descripcion';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_factor_riesgo_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_factor_riesgo_nna'), N'orden', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Orden numÃ©rico de presentaciÃ³n del Ã­tem dentro de su categorÃ­a.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna',@level2type=N'COLUMN',@level2name=N'orden';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.cat_factor_riesgo_nna') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.cat_factor_riesgo_nna'), N'es_activo', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Indicador lÃ³gico de actividad del Ã­tem. 1 = activo, 0 = inactivo (preserva trazabilidad histÃ³rica).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna',@level2type=N'COLUMN',@level2name=N'es_activo';

IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_factor_riesgo_nna', N'CONSTRAINT', N'pk_cat_factor_riesgo_nna'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Clave primaria autonumÃ©rica del catÃ¡logo.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna',@level2type=N'CONSTRAINT',@level2name=N'pk_cat_factor_riesgo_nna';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_factor_riesgo_nna', N'CONSTRAINT', N'uq_cat_factor_riesgo_nna_codigo'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Garantiza que el cÃ³digo del Ã­tem sea Ãºnico en el catÃ¡logo.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna',@level2type=N'CONSTRAINT',@level2name=N'uq_cat_factor_riesgo_nna_codigo';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_factor_riesgo_nna', N'CONSTRAINT', N'fk_cat_factor_riesgo_nna_categoria'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a denuncias.cat_categoria_factor_riesgo_nna: secciÃ³n del Anexo NÂ°3 a la que pertenece el Ã­tem.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna',@level2type=N'CONSTRAINT',@level2name=N'fk_cat_factor_riesgo_nna_categoria';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_factor_riesgo_nna', N'CONSTRAINT', N'df_cat_factor_riesgo_nna_es_activo'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Valor por defecto de es_activo: todo Ã­tem nuevo nace activo (1).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna',@level2type=N'CONSTRAINT',@level2name=N'df_cat_factor_riesgo_nna_es_activo';

-- â”€â”€â”€ denuncias.pauta_nna_factor_riesgo â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo') AND minor_id = 0 AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Respuesta (SI/NO/NO_SABE) y observaciÃ³n para cada Ã­tem del checklist del Anexo NÂ°3, por pauta_nna.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo'), N'id_pauta_nna_factor_riesgo', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Identificador Ãºnico de la respuesta. Clave primaria autogenerada por el motor.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'COLUMN',@level2name=N'id_pauta_nna_factor_riesgo';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo'), N'id_pauta_nna', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a denuncias.pauta_nna: pauta a la que pertenece esta respuesta.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'COLUMN',@level2name=N'id_pauta_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo'), N'id_factor_riesgo_nna', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a denuncias.cat_factor_riesgo_nna: Ã­tem del checklist respondido.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'COLUMN',@level2name=N'id_factor_riesgo_nna';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo'), N'respuesta', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Respuesta al Ã­tem del checklist. Dominio cerrado: SI, NO, NO_SABE.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'COLUMN',@level2name=N'respuesta';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo'), N'observaciones', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'ObservaciÃ³n libre asociada a la respuesta del Ã­tem.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'COLUMN',@level2name=N'observaciones';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo'), N'fecha_creacion', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Fecha/hora UTC de creaciÃ³n del registro. Asignada por el motor via CURRENT_TIMESTAMP.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'COLUMN',@level2name=N'fecha_creacion';
IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo') AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'denuncias.pauta_nna_factor_riesgo'), N'fecha_actualizacion', 'ColumnId') AND name = N'MS_Description')
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Fecha/hora UTC de la Ãºltima actualizaciÃ³n del registro. NULL si nunca se ha modificado.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'COLUMN',@level2name=N'fecha_actualizacion';

-- â”€â”€â”€ Restricciones e Ã­ndices â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna_factor_riesgo', N'CONSTRAINT', N'pk_pauta_nna_factor_riesgo'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Clave primaria autonumÃ©rica de la respuesta.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'CONSTRAINT',@level2name=N'pk_pauta_nna_factor_riesgo';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna_factor_riesgo', N'CONSTRAINT', N'fk_pauta_nna_factor_riesgo_pauta'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a denuncias.pauta_nna: pauta a la que pertenece esta respuesta.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'CONSTRAINT',@level2name=N'fk_pauta_nna_factor_riesgo_pauta';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna_factor_riesgo', N'CONSTRAINT', N'fk_pauta_nna_factor_riesgo_factor'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK a denuncias.cat_factor_riesgo_nna: Ã­tem del checklist respondido.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'CONSTRAINT',@level2name=N'fk_pauta_nna_factor_riesgo_factor';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna_factor_riesgo', N'CONSTRAINT', N'df_pauta_nna_factor_riesgo_fecha_creacion'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Valor por defecto de fecha_creacion: red de seguridad para asegurar UTC aunque el procedimiento no la puebla explÃ­citamente.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'CONSTRAINT',@level2name=N'df_pauta_nna_factor_riesgo_fecha_creacion';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna', N'CONSTRAINT', N'fk_pauta_nna_denuncia'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK opcional: pauta_nna.id_denuncia â†’ denuncias.denuncia.id_denuncia.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'CONSTRAINT',@level2name=N'fk_pauta_nna_denuncia';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna', N'CONSTRAINT', N'fk_pauta_nna_caso'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'FK opcional: pauta_nna.id_caso â†’ casos.caso.id_caso.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'CONSTRAINT',@level2name=N'fk_pauta_nna_caso';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna', N'INDEX', N'ix_pauta_nna_denuncia'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Ãndice filtrado (id_denuncia IS NOT NULL) para bÃºsquedas de pauta_nna por denuncia.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'INDEX',@level2name=N'ix_pauta_nna_denuncia';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna', N'INDEX', N'ix_pauta_nna_caso'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Ãndice filtrado (id_caso IS NOT NULL) para bÃºsquedas de pauta_nna por caso.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna',@level2type=N'INDEX',@level2name=N'ix_pauta_nna_caso';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'cat_factor_riesgo_nna', N'INDEX', N'ix_cat_factor_riesgo_nna_categoria'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Ãndice de soporte para el JOIN de cat_factor_riesgo_nna con su categorÃ­a.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'cat_factor_riesgo_nna',@level2type=N'INDEX',@level2name=N'ix_cat_factor_riesgo_nna_categoria';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna_factor_riesgo', N'INDEX', N'ix_pauta_nna_factor_riesgo_pauta'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Ãndice de soporte para listar las respuestas del checklist de una pauta_nna.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'INDEX',@level2name=N'ix_pauta_nna_factor_riesgo_pauta';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna_factor_riesgo', N'CONSTRAINT', N'uq_pauta_nna_factor_riesgo'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Garantiza una Ãºnica respuesta por combinaciÃ³n (pauta_nna, factor_riesgo_nna).',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'CONSTRAINT',@level2name=N'uq_pauta_nna_factor_riesgo';
IF NOT EXISTS (SELECT 1 FROM fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'denuncias', N'TABLE', N'pauta_nna_factor_riesgo', N'CONSTRAINT', N'ck_pauta_nna_factor_riesgo_respuesta'))
 EXEC sys.sp_addextendedproperty @name=N'MS_Description',
 @value=N'Restringe respuesta al dominio cerrado SI/NO/NO_SABE.',
 @level0type=N'SCHEMA',@level0name=N'denuncias',@level1type=N'TABLE',@level1name=N'pauta_nna_factor_riesgo',@level2type=N'CONSTRAINT',@level2name=N'ck_pauta_nna_factor_riesgo_respuesta';

