-- =============================================================================
-- V0040 -- Descripciones (MS_Description) del esquema archivos
-- PDI Chile -- SIP. SQL Server. Flyway.
--
-- Documenta a nivel de base de datos las 4 tablas del esquema archivos y todas
-- sus columnas (estado posterior a V0039). Objetivo: mantenibilidad -- la
-- documentacion vive junto al modelo y se lee desde sys.extended_properties.
--
-- Tablas: cat_tipo_archivo, archivo, archivo_vinculo, cat_entidad_vinculable.
-- Patron: drop-then-add (idempotente y actualizable en cada corrida),
-- identico a V0005.
-- =============================================================================

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
SET NOCOUNT ON;

-- =============================================================================
-- Tabla: archivos.cat_tipo_archivo
-- =============================================================================

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.tables t ON ep.major_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description' AND ep.minor_id = 0
 AND s.name = N'archivos' AND t.name = N'cat_tipo_archivo'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'CatÃ¡logo de tipos de archivo del sistema (documento, imagen, video, etc.). Clasifica cada fila de archivos.archivo. PatrÃ³n de catÃ¡logo: 5 columnas de auditorÃ­a (omite id_usuario_creador).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_tipo_archivo' AND c.name = N'id_tipo_archivo'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'id_tipo_archivo';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Identificador Ãºnico del tipo de archivo. Clave primaria autogenerada (generated by default as identity).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'id_tipo_archivo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_tipo_archivo' AND c.name = N'codigo'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'codigo';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'CÃ³digo Ãºnico y estable del tipo de archivo (p. ej. ''PDF'', ''IMG'', ''VIDEO''). Uso programÃ¡tico; UNIQUE.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'codigo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_tipo_archivo' AND c.name = N'nombre'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'nombre';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Nombre legible del tipo de archivo para presentaciÃ³n al usuario.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'nombre';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_tipo_archivo' AND c.name = N'es_multimedia'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'es_multimedia';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Indica si el tipo corresponde a contenido multimedia (audio, video, imagen). 1 = sÃ­, 0 = no. CHECK (0,1).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'es_multimedia';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_tipo_archivo' AND c.name = N'tamanio_max_mb'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'tamanio_max_mb';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'TamaÃ±o mÃ¡ximo permitido en MB para archivos de este tipo. NULL = sin lÃ­mite especÃ­fico del tipo (rige el lÃ­mite global de la plataforma).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'tamanio_max_mb';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_tipo_archivo' AND c.name = N'id_usuario_modificador'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_modificador';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Usuario de la Ãºltima modificaciÃ³n del registro (auditorÃ­a). Referencia lÃ³gica a auth.usuario, sin FK fÃ­sica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_modificador';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_tipo_archivo' AND c.name = N'id_usuario_eliminador'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_eliminador';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Usuario que efectuÃ³ la baja lÃ³gica del registro (auditorÃ­a). Referencia lÃ³gica a auth.usuario, sin FK fÃ­sica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_eliminador';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_tipo_archivo' AND c.name = N'fecha_creacion'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_creacion';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Marca temporal de creaciÃ³n del registro (UTC).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_creacion';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_tipo_archivo' AND c.name = N'fecha_actualizacion'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_actualizacion';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Marca temporal de la Ãºltima actualizaciÃ³n del registro (UTC).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_actualizacion';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_tipo_archivo' AND c.name = N'fecha_eliminacion_logica'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_eliminacion_logica';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Marca temporal de la baja lÃ³gica. NULL = registro vigente. Los registros no se borran fÃ­sicamente; la eliminaciÃ³n es siempre lÃ³gica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_tipo_archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_eliminacion_logica';


-- =============================================================================
-- Tabla: archivos.archivo
-- =============================================================================

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.tables t ON ep.major_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description' AND ep.minor_id = 0
 AND s.name = N'archivos' AND t.name = N'archivo'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Metadata y ubicaciÃ³n de cada archivo fÃ­sico cargado en el sistema. El contenido binario reside en almacenamiento externo; la columna ruta apunta a Ã©l. Entidad central del subsistema de archivos.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'id_archivo'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_archivo';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Identificador Ãºnico del archivo. Clave primaria autogenerada (generated by default as identity).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_archivo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'nombre_original'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'nombre_original';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Nombre original del archivo tal como lo cargÃ³ el usuario. Valor descriptivo.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'nombre_original';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'nombre_almacenado'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'nombre_almacenado';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Nombre con que el archivo se persiste en el almacenamiento (normalizado y Ãºnico). Evita colisiones y caracteres invÃ¡lidos.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'nombre_almacenado';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'ruta'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'ruta';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Ruta o clave de ubicaciÃ³n del archivo en el almacenamiento fÃ­sico externo.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'ruta';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'mime_type'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'mime_type';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Tipo MIME del contenido (p. ej. ''application/pdf'', ''image/jpeg''). Determina el manejo del archivo.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'mime_type';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'extension'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'extension';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'ExtensiÃ³n del archivo sin el punto (p. ej. ''pdf''). Informativa.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'extension';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'tamano_bytes'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'tamano_bytes';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'TamaÃ±o del archivo en bytes.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'tamano_bytes';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'hash_sha256'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'hash_sha256';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Hash SHA-256 del contenido. Permite verificar integridad y detectar duplicados.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'hash_sha256';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'id_tipo_archivo'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_tipo_archivo';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Tipo de archivo. FK a archivos.cat_tipo_archivo.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_tipo_archivo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'id_funcionario_carga'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_funcionario_carga';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Funcionario que realizÃ³ la carga del archivo. Referencia a organizacion.funcionario.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_funcionario_carga';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'origen'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'origen';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Origen o canal de la carga (mÃ³dulo, proceso o sistema que originÃ³ el archivo).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'origen';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'id_archivo_version_anterior'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_archivo_version_anterior';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'VersiÃ³n inmediatamente anterior del mismo archivo. FK recursiva a archivos.archivo; encadena el historial de versiones. NULL en la primera versiÃ³n.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_archivo_version_anterior';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'numero_version'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'numero_version';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'NÃºmero de versiÃ³n del archivo dentro de su cadena de versiones. Inicia en 1.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'numero_version';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'fecha_carga'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_carga';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Fecha y hora de la carga del archivo (UTC).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_carga';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'fecha_eliminacion_logica'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_eliminacion_logica';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Marca temporal de la baja lÃ³gica. NULL = registro vigente. Los registros no se borran fÃ­sicamente; la eliminaciÃ³n es siempre lÃ³gica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_eliminacion_logica';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'motivo_eliminacion'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'motivo_eliminacion';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Motivo registrado al dar de baja lÃ³gica el archivo. NULL si el archivo estÃ¡ vigente.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'motivo_eliminacion';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'id_usuario_creador'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_creador';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Usuario que creÃ³ el registro (auditorÃ­a). Referencia lÃ³gica a auth.usuario; sin FK fÃ­sica (la integridad de auditorÃ­a se delega a la aplicaciÃ³n, ver V0032).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_creador';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'id_usuario_modificador'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_modificador';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Usuario de la Ãºltima modificaciÃ³n del registro (auditorÃ­a). Referencia lÃ³gica a auth.usuario, sin FK fÃ­sica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_modificador';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'id_usuario_eliminador'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_eliminador';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Usuario que efectuÃ³ la baja lÃ³gica del registro (auditorÃ­a). Referencia lÃ³gica a auth.usuario, sin FK fÃ­sica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_eliminador';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'fecha_creacion'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_creacion';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Marca temporal de creaciÃ³n del registro (UTC).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_creacion';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo' AND c.name = N'fecha_actualizacion'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_actualizacion';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Marca temporal de la Ãºltima actualizaciÃ³n del registro (UTC).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo',
 @level2type = N'COLUMN', @level2name = N'fecha_actualizacion';


-- =============================================================================
-- Tabla: archivos.archivo_vinculo
-- =============================================================================

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.tables t ON ep.major_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description' AND ep.minor_id = 0
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'AsociaciÃ³n polimÃ³rfica entre un archivo y una entidad de negocio. Permite vincular un mismo archivo a cualquier entidad declarada en archivos.cat_entidad_vinculable (relaciÃ³n M:N). PatrÃ³n polimÃ³rfico: la referencia a la fila (id_entidad) no tiene FK fÃ­sica; su integridad se valida en la capa de aplicaciÃ³n (procedimiento validador) y con un detector de huÃ©rfanos.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo' AND c.name = N'id_archivo_vinculo'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_archivo_vinculo';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Identificador Ãºnico del vÃ­nculo. Clave primaria autogenerada (generated by default as identity). Antes ''id_vinculo'' (renombrado en V0039).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_archivo_vinculo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo' AND c.name = N'id_archivo'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_archivo';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Archivo vinculado. FK a archivos.archivo.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_archivo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo' AND c.name = N'id_entidad_vinculable'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_entidad_vinculable';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Entidad de negocio a la que se asocia el archivo (indica QUÃ‰ tabla). FK a archivos.cat_entidad_vinculable. Junto con id_entidad resuelve la referencia polimÃ³rfica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_entidad_vinculable';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo' AND c.name = N'id_entidad'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_entidad';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Identificador de la fila especÃ­fica dentro de la tabla indicada por id_entidad_vinculable (indica CUÃL fila). Sin FK fÃ­sica, por diseÃ±o polimÃ³rfico; su existencia se valida en la aplicaciÃ³n.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_entidad';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo' AND c.name = N'rol_archivo'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'rol_archivo';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Rol o propÃ³sito del archivo dentro de la entidad vinculada (p. ej. ''ADJUNTO'', ''FOTO_PERFIL''). Opcional.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'rol_archivo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo' AND c.name = N'fecha_vinculo'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'fecha_vinculo';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Fecha y hora en que se creÃ³ el vÃ­nculo (UTC).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'fecha_vinculo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo' AND c.name = N'id_usuario_creador'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_creador';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Usuario que creÃ³ el registro (auditorÃ­a). Referencia lÃ³gica a auth.usuario; sin FK fÃ­sica (la integridad de auditorÃ­a se delega a la aplicaciÃ³n, ver V0032).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_creador';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo' AND c.name = N'id_usuario_modificador'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_modificador';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Usuario de la Ãºltima modificaciÃ³n del registro (auditorÃ­a). Referencia lÃ³gica a auth.usuario, sin FK fÃ­sica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_modificador';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo' AND c.name = N'id_usuario_eliminador'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_eliminador';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Usuario que efectuÃ³ la baja lÃ³gica del registro (auditorÃ­a). Referencia lÃ³gica a auth.usuario, sin FK fÃ­sica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'id_usuario_eliminador';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo' AND c.name = N'fecha_creacion'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'fecha_creacion';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Marca temporal de creaciÃ³n del registro (UTC).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'fecha_creacion';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo' AND c.name = N'fecha_actualizacion'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'fecha_actualizacion';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Marca temporal de la Ãºltima actualizaciÃ³n del registro (UTC).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'fecha_actualizacion';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'archivo_vinculo' AND c.name = N'fecha_eliminacion_logica'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'fecha_eliminacion_logica';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Marca temporal de la baja lÃ³gica. NULL = registro vigente. Los registros no se borran fÃ­sicamente; la eliminaciÃ³n es siempre lÃ³gica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'archivo_vinculo',
 @level2type = N'COLUMN', @level2name = N'fecha_eliminacion_logica';


-- =============================================================================
-- Tabla: archivos.cat_entidad_vinculable
-- =============================================================================

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.tables t ON ep.major_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description' AND ep.minor_id = 0
 AND s.name = N'archivos' AND t.name = N'cat_entidad_vinculable'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'CatÃ¡logo de entidades de negocio a las que se puede asociar un archivo mediante el vÃ­nculo polimÃ³rfico (archivos.archivo_vinculo). Cada fila declara una tabla vinculable con su esquema, su nombre y su columna PK, que el procedimiento validador usa para comprobar la existencia de la fila referenciada. No tiene FK hacia los dominios: esa ausencia mantiene el desacople entre esquemas. PatrÃ³n de catÃ¡logo: 5 columnas de auditorÃ­a. Los id_entidad_vinculable son permanentes: una vez asignados no se reutilizan ni se reasignan, ni siquiera si la entidad se elimina o inhabilita, para no invalidar los vÃ­nculos existentes en archivo_vinculo (por eso el seed puede dejar huecos en la numeraciÃ³n).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_entidad_vinculable' AND c.name = N'id_entidad_vinculable'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'id_entidad_vinculable';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Identificador Ãºnico de la entidad vinculable. Clave primaria (generated by default as identity). Es el valor referenciado por archivos.archivo_vinculo.id_entidad_vinculable. Los ids se siembran de forma explÃ­cita y son permanentes: estables entre ambientes (dev/QA/prod) y nunca se reutilizan ni reasignan una vez usados, ni siquiera si la entidad se elimina o inhabilita.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'id_entidad_vinculable';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_entidad_vinculable' AND c.name = N'esquema'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'esquema';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Nombre del esquema de la tabla vinculable (p. ej. ''denuncias''). Parte de la identificaciÃ³n de la entidad.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'esquema';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_entidad_vinculable' AND c.name = N'entidad'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'entidad';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Nombre de la tabla vinculable a la que se puede asociar un archivo (p. ej. ''denuncia''). Junto con esquema forma la clave Ãºnica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'entidad';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_entidad_vinculable' AND c.name = N'columna_pk'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'columna_pk';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Nombre de la columna de clave primaria de la tabla vinculable (p. ej. ''id_denuncia''). La usa el procedimiento validador para comprobar la existencia de la fila referenciada.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'columna_pk';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_entidad_vinculable' AND c.name = N'activo'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'activo';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Habilita (1) o inhabilita (0) la entidad como destino de vÃ­nculos, sin eliminar la fila. Default 1.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'activo';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_entidad_vinculable' AND c.name = N'id_usuario_modificador'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'id_usuario_modificador';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Usuario de la Ãºltima modificaciÃ³n del registro (auditorÃ­a). Referencia lÃ³gica a auth.usuario, sin FK fÃ­sica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'id_usuario_modificador';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_entidad_vinculable' AND c.name = N'id_usuario_eliminador'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'id_usuario_eliminador';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Usuario que efectuÃ³ la baja lÃ³gica del registro (auditorÃ­a). Referencia lÃ³gica a auth.usuario, sin FK fÃ­sica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'id_usuario_eliminador';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_entidad_vinculable' AND c.name = N'fecha_creacion'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'fecha_creacion';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Marca temporal de creaciÃ³n del registro (UTC).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'fecha_creacion';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_entidad_vinculable' AND c.name = N'fecha_actualizacion'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'fecha_actualizacion';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Marca temporal de la Ãºltima actualizaciÃ³n del registro (UTC).',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'fecha_actualizacion';

IF EXISTS (
 SELECT 1 FROM sys.extended_properties ep
 INNER JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id
 INNER JOIN sys.tables t ON c.object_id = t.object_id
 INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
 WHERE ep.name = N'MS_Description'
 AND s.name = N'archivos' AND t.name = N'cat_entidad_vinculable' AND c.name = N'fecha_eliminacion_logica'
)
 EXEC sys.sp_dropextendedproperty
 @name = N'MS_Description',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'fecha_eliminacion_logica';
EXEC sys.sp_addextendedproperty
 @name = N'MS_Description',
 @value = N'Marca temporal de la baja lÃ³gica. NULL = registro vigente. Los registros no se borran fÃ­sicamente; la eliminaciÃ³n es siempre lÃ³gica.',
 @level0type = N'SCHEMA', @level0name = N'archivos',
 @level1type = N'TABLE', @level1name = N'cat_entidad_vinculable',
 @level2type = N'COLUMN', @level2name = N'fecha_eliminacion_logica';


