Param(
    [string]$RepoRoot = ".",
    [string]$InRoot = "migration_postgres/output/source",
    [string]$OutRoot = "migration_postgres/output/postgres"
)

$ErrorActionPreference = "Stop"

$repo = Resolve-Path $RepoRoot
$inBase = Join-Path $repo $InRoot
$outBase = Join-Path $repo $OutRoot
$reportDir = Join-Path $repo "migration_postgres/output/reports"

if (-not (Test-Path $inBase)) { throw "No existe input: $inBase" }

New-Item -ItemType Directory -Force -Path $outBase | Out-Null
New-Item -ItemType Directory -Force -Path $reportDir | Out-Null

$replacements = @(
    @{ Pattern = "\r\nGO\r\n|\nGO\n|\r\nGO\n|\nGO\r\n"; Value = "`n" },
    @{ Pattern = "(?im)^\s*GO\s*$"; Value = "" },
    @{ Pattern = "\["; Value = "" },
    @{ Pattern = "\]"; Value = "" },
    @{ Pattern = "(?i)IDENTITY\s*\(\s*1\s*,\s*1\s*\)"; Value = "generated by default as identity" },
    @{ Pattern = "(?i)\bIDENTITY\b(?!\s*\()"; Value = "generated by default as identity" },
    @{ Pattern = "(?i)DATETIME2\s*\(\s*\d+\s*\)"; Value = "timestamp" },
    @{ Pattern = "(?i)\bDATETIME\b"; Value = "timestamp" },
    @{ Pattern = "(?i)\bNVARCHAR\s*\(\s*MAX\s*\)"; Value = "text" },
    @{ Pattern = "(?i)\bNVARCHAR\s*\("; Value = "varchar(" },
    @{ Pattern = "(?i)\bUNIQUEIDENTIFIER\b"; Value = "uuid" },
    @{ Pattern = "(?i)\bBIT\b"; Value = "boolean" },
    @{ Pattern = "(?i)\bTINYINT\b"; Value = "smallint" },
    @{ Pattern = "(?i)\bSYSUTCDATETIME\s*\(\s*\)"; Value = "CURRENT_TIMESTAMP" },
    @{ Pattern = "(?i)\bGETDATE\s*\(\s*\)"; Value = "CURRENT_TIMESTAMP" },
    @{ Pattern = "(?i)\s+ON\s+PRIMARY"; Value = "" },
    @{ Pattern = "(?i)WITH\s*\(PAD_INDEX\s*=.*?\)\s*"; Value = "" }
)

$files = Get-ChildItem -Path $inBase -Filter "*.sql" -Recurse | Sort-Object FullName

foreach ($f in $files) {
    $relative = $f.FullName.Substring($inBase.Length).TrimStart([char]'\', [char]'/')
    $target = Join-Path $outBase $relative
    $targetDir = Split-Path $target -Parent
    New-Item -ItemType Directory -Force -Path $targetDir | Out-Null

    $text = Get-Content -Path $f.FullName -Raw

    foreach ($r in $replacements) {
        $text = [regex]::Replace($text, $r.Pattern, $r.Value)
    }

    # Limpieza de dobles espacios en lineas de DDL por remocion parcial.
    $text = [regex]::Replace($text, "[ \t]{2,}", " ")

    Set-Content -Path $target -Value $text -Encoding UTF8
}

Write-Output "Conversion completada"
Write-Output "Output -> $outBase"

# Reporte simple de patrones pendientes.
$pendingPatterns = @(
    'PERSISTED',
    'sp_addextendedproperty',
    'MERGE\s+.*\s+USING',
    'TRY_CONVERT',
    'SCOPE_IDENTITY\s*\(',
    'OPENJSON',
    'JSON_VALUE',
    'WITH\s*\('
)

$reportPath = Join-Path $reportDir "pending_patterns_report.txt"
"Pending patterns report" | Set-Content -Path $reportPath -Encoding UTF8
"Generated: $(Get-Date -Format o)" | Add-Content -Path $reportPath
"" | Add-Content -Path $reportPath

foreach ($pp in $pendingPatterns) {
    $sqlFiles = Get-ChildItem -Path $outBase -Filter "*.sql" -Recurse
    $count = (Select-String -Path $sqlFiles.FullName -Pattern $pp -AllMatches -CaseSensitive:$false -ErrorAction SilentlyContinue | Measure-Object).Count
    Add-Content -Path $reportPath -Value ("{0} => {1}" -f $pp, $count)
}

Write-Output "Reporte -> $reportPath"
